//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Eurobank;

[assembly: RegisterCustomTable(Polls_UsersItem.CLASS_NAME, typeof(Polls_UsersItem))]

namespace CMS.CustomTables.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type Polls_UsersItem.
	/// </summary>
	public partial class Polls_UsersItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.Polls_Users";


		/// <summary>
		/// The instance of the class that provides extended API for working with Polls_UsersItem fields.
		/// </summary>
		private readonly Polls_UsersItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Polls ID.
		/// </summary>
		[DatabaseField]
		public string PollsID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PollsID"), @"");
			}
			set
			{
				SetValue("PollsID", value);
			}
		}


		/// <summary>
		/// Answer ID.
		/// </summary>
		[DatabaseField]
		public string AnswerID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AnswerID"), @"");
			}
			set
			{
				SetValue("AnswerID", value);
			}
		}


		/// <summary>
		/// User ID.
		/// </summary>
		[DatabaseField]
		public string UserID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UserID"), @"");
			}
			set
			{
				SetValue("UserID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Polls_UsersItem fields.
		/// </summary>
		[RegisterProperty]
		public Polls_UsersItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Polls_UsersItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class Polls_UsersItemFields : AbstractHierarchicalObject<Polls_UsersItemFields>
		{
			/// <summary>
			/// The content item of type Polls_UsersItem that is a target of the extended API.
			/// </summary>
			private readonly Polls_UsersItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="Polls_UsersItemFields" /> class with the specified content item of type Polls_UsersItem.
			/// </summary>
			/// <param name="instance">The content item of type Polls_UsersItem that is a target of the extended API.</param>
			public Polls_UsersItemFields(Polls_UsersItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Polls ID.
			/// </summary>
			public string PollsID
			{
				get
				{
					return mInstance.PollsID;
				}
				set
				{
					mInstance.PollsID = value;
				}
			}


			/// <summary>
			/// Answer ID.
			/// </summary>
			public string AnswerID
			{
				get
				{
					return mInstance.AnswerID;
				}
				set
				{
					mInstance.AnswerID = value;
				}
			}


			/// <summary>
			/// User ID.
			/// </summary>
			public string UserID
			{
				get
				{
					return mInstance.UserID;
				}
				set
				{
					mInstance.UserID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Polls_UsersItem" /> class.
		/// </summary>
		public Polls_UsersItem() : base(CLASS_NAME)
		{
			mFields = new Polls_UsersItemFields(this);
		}

		#endregion
	}
}