//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(BankDocuments.CLASS_NAME, typeof(BankDocuments))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type BankDocuments.
	/// </summary>
	public partial class BankDocuments : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.BankDocuments";


		/// <summary>
		/// The instance of the class that provides extended API for working with BankDocuments fields.
		/// </summary>
		private readonly BankDocumentsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BankDocumentsID.
		/// </summary>
		[DatabaseIDField]
		public int BankDocumentsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BankDocumentsID"), 0);
			}
			set
			{
				SetValue("BankDocumentsID", value);
			}
		}


		/// <summary>
		/// Bank Documents Status.
		/// </summary>
		[DatabaseField]
		public bool BankDocuments_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("BankDocuments_Status"), false);
			}
			set
			{
				SetValue("BankDocuments_Status", value);
			}
		}


		/// <summary>
		/// Entity Name.
		/// </summary>
		[DatabaseField]
		public Guid BankDocuments_Entity
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BankDocuments_Entity"), Guid.Empty);
			}
			set
			{
				SetValue("BankDocuments_Entity", value);
			}
		}


		/// <summary>
		/// Entity Type.
		/// </summary>
		[DatabaseField]
		public Guid BankDocuments_EntityType
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BankDocuments_EntityType"), Guid.Empty);
			}
			set
			{
				SetValue("BankDocuments_EntityType", value);
			}
		}


		/// <summary>
		/// Entity Role.
		/// </summary>
		[DatabaseField]
		public Guid BankDocuments_EntityRole
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BankDocuments_EntityRole"), Guid.Empty);
			}
			set
			{
				SetValue("BankDocuments_EntityRole", value);
			}
		}


		/// <summary>
		/// Document Type.
		/// </summary>
		[DatabaseField]
		public Guid BankDocuments_DocumentType
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BankDocuments_DocumentType"), Guid.Empty);
			}
			set
			{
				SetValue("BankDocuments_DocumentType", value);
			}
		}


		/// <summary>
		/// Requires Signature.
		/// </summary>
		[DatabaseField]
		public bool BankDocuments_RequiresSignature
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("BankDocuments_RequiresSignature"), true);
			}
			set
			{
				SetValue("BankDocuments_RequiresSignature", value);
			}
		}


		/// <summary>
		/// File upload.
		/// </summary>
		[DatabaseField]
		public string BankDocuments_FileUpload
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankDocuments_FileUpload"), @"");
			}
			set
			{
				SetValue("BankDocuments_FileUpload", value);
			}
		}


		/// <summary>
		/// Confirm validity of document and signature where it applies.
		/// </summary>
		[DatabaseField]
		public bool BankDocuments_Consent
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("BankDocuments_Consent"), false);
			}
			set
			{
				SetValue("BankDocuments_Consent", value);
			}
		}


		/// <summary>
		/// File Name.
		/// </summary>
		[DatabaseField]
		public string FileName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FileName"), @"");
			}
			set
			{
				SetValue("FileName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BankDocuments fields.
		/// </summary>
		[RegisterProperty]
		public BankDocumentsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BankDocuments fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BankDocumentsFields : AbstractHierarchicalObject<BankDocumentsFields>
		{
			/// <summary>
			/// The content item of type BankDocuments that is a target of the extended API.
			/// </summary>
			private readonly BankDocuments mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BankDocumentsFields" /> class with the specified content item of type BankDocuments.
			/// </summary>
			/// <param name="instance">The content item of type BankDocuments that is a target of the extended API.</param>
			public BankDocumentsFields(BankDocuments instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BankDocumentsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BankDocumentsID;
				}
				set
				{
					mInstance.BankDocumentsID = value;
				}
			}


			/// <summary>
			/// Bank Documents Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.BankDocuments_Status;
				}
				set
				{
					mInstance.BankDocuments_Status = value;
				}
			}


			/// <summary>
			/// Entity Name.
			/// </summary>
			public Guid _Entity
			{
				get
				{
					return mInstance.BankDocuments_Entity;
				}
				set
				{
					mInstance.BankDocuments_Entity = value;
				}
			}


			/// <summary>
			/// Entity Type.
			/// </summary>
			public Guid _EntityType
			{
				get
				{
					return mInstance.BankDocuments_EntityType;
				}
				set
				{
					mInstance.BankDocuments_EntityType = value;
				}
			}


			/// <summary>
			/// Entity Role.
			/// </summary>
			public Guid _EntityRole
			{
				get
				{
					return mInstance.BankDocuments_EntityRole;
				}
				set
				{
					mInstance.BankDocuments_EntityRole = value;
				}
			}


			/// <summary>
			/// Document Type.
			/// </summary>
			public Guid _DocumentType
			{
				get
				{
					return mInstance.BankDocuments_DocumentType;
				}
				set
				{
					mInstance.BankDocuments_DocumentType = value;
				}
			}


			/// <summary>
			/// Requires Signature.
			/// </summary>
			public bool _RequiresSignature
			{
				get
				{
					return mInstance.BankDocuments_RequiresSignature;
				}
				set
				{
					mInstance.BankDocuments_RequiresSignature = value;
				}
			}


			/// <summary>
			/// File upload.
			/// </summary>
			public string _FileUpload
			{
				get
				{
					return mInstance.BankDocuments_FileUpload;
				}
				set
				{
					mInstance.BankDocuments_FileUpload = value;
				}
			}


			/// <summary>
			/// Confirm validity of document and signature where it applies.
			/// </summary>
			public bool _Consent
			{
				get
				{
					return mInstance.BankDocuments_Consent;
				}
				set
				{
					mInstance.BankDocuments_Consent = value;
				}
			}


			/// <summary>
			/// File Name.
			/// </summary>
			public string FileName
			{
				get
				{
					return mInstance.FileName;
				}
				set
				{
					mInstance.FileName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BankDocuments" /> class.
		/// </summary>
		public BankDocuments() : base(CLASS_NAME)
		{
			mFields = new BankDocumentsFields(this);
		}

		#endregion
	}
}