//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(News.CLASS_NAME, typeof(News))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type News.
	/// </summary>
	public partial class News : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.News";


		/// <summary>
		/// The instance of the class that provides extended API for working with News fields.
		/// </summary>
		private readonly NewsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NewsID.
		/// </summary>
		[DatabaseIDField]
		public int NewsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NewsID"), 0);
			}
			set
			{
				SetValue("NewsID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string NewsTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NewsTitle"), @"");
			}
			set
			{
				SetValue("NewsTitle", value);
			}
		}


		/// <summary>
		/// Teaser.
		/// </summary>
		[DatabaseField]
		public Guid NewsTeaser
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("NewsTeaser"), Guid.Empty);
			}
			set
			{
				SetValue("NewsTeaser", value);
			}
		}


		/// <summary>
		/// News Summary.
		/// </summary>
		[DatabaseField]
		public string NewsSummary
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NewsSummary"), @"");
			}
			set
			{
				SetValue("NewsSummary", value);
			}
		}


		/// <summary>
		/// News Long Description.
		/// </summary>
		[DatabaseField]
		public string NewsLongDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("NewsLongDescription"), @"");
			}
			set
			{
				SetValue("NewsLongDescription", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with News fields.
		/// </summary>
		[RegisterProperty]
		public NewsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with News fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class NewsFields : AbstractHierarchicalObject<NewsFields>
		{
			/// <summary>
			/// The content item of type News that is a target of the extended API.
			/// </summary>
			private readonly News mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="NewsFields" /> class with the specified content item of type News.
			/// </summary>
			/// <param name="instance">The content item of type News that is a target of the extended API.</param>
			public NewsFields(News instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NewsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.NewsID;
				}
				set
				{
					mInstance.NewsID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.NewsTitle;
				}
				set
				{
					mInstance.NewsTitle = value;
				}
			}


			/// <summary>
			/// Teaser.
			/// </summary>
			public DocumentAttachment Teaser
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("NewsTeaser");
				}
			}


			/// <summary>
			/// News Summary.
			/// </summary>
			public string Summary
			{
				get
				{
					return mInstance.NewsSummary;
				}
				set
				{
					mInstance.NewsSummary = value;
				}
			}


			/// <summary>
			/// News Long Description.
			/// </summary>
			public string LongDescription
			{
				get
				{
					return mInstance.NewsLongDescription;
				}
				set
				{
					mInstance.NewsLongDescription = value;
				}
			}


			/// <summary>
			/// Related News.
			/// </summary>
			public IEnumerable<TreeNode> RelatedNews
			{
				get
				{
					return mInstance.GetRelatedDocuments("NewsRelatedNews");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="News" /> class.
		/// </summary>
		public News() : base(CLASS_NAME)
		{
			mFields = new NewsFields(this);
		}

		#endregion
	}
}