//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(WhatsNew.CLASS_NAME, typeof(WhatsNew))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type WhatsNew.
	/// </summary>
	public partial class WhatsNew : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.WhatsNew";


		/// <summary>
		/// The instance of the class that provides extended API for working with WhatsNew fields.
		/// </summary>
		private readonly WhatsNewFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// WhatsNewID.
		/// </summary>
		[DatabaseIDField]
		public int WhatsNewID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("WhatsNewID"), 0);
			}
			set
			{
				SetValue("WhatsNewID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Teaser.
		/// </summary>
		[DatabaseField]
		public Guid Teaser
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Teaser"), Guid.Empty);
			}
			set
			{
				SetValue("Teaser", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WhatsNew fields.
		/// </summary>
		[RegisterProperty]
		public WhatsNewFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WhatsNew fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WhatsNewFields : AbstractHierarchicalObject<WhatsNewFields>
		{
			/// <summary>
			/// The content item of type WhatsNew that is a target of the extended API.
			/// </summary>
			private readonly WhatsNew mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WhatsNewFields" /> class with the specified content item of type WhatsNew.
			/// </summary>
			/// <param name="instance">The content item of type WhatsNew that is a target of the extended API.</param>
			public WhatsNewFields(WhatsNew instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// WhatsNewID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.WhatsNewID;
				}
				set
				{
					mInstance.WhatsNewID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Teaser.
			/// </summary>
			public DocumentAttachment Teaser
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("Teaser");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WhatsNew" /> class.
		/// </summary>
		public WhatsNew() : base(CLASS_NAME)
		{
			mFields = new WhatsNewFields(this);
		}

		#endregion
	}
}