//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(WhatsNewSection.CLASS_NAME, typeof(WhatsNewSection))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type WhatsNewSection.
	/// </summary>
	public partial class WhatsNewSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.WhatsNewSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with WhatsNewSection fields.
		/// </summary>
		private readonly WhatsNewSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// WhatsNewSectionID.
		/// </summary>
		[DatabaseIDField]
		public int WhatsNewSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("WhatsNewSectionID"), 0);
			}
			set
			{
				SetValue("WhatsNewSectionID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with WhatsNewSection fields.
		/// </summary>
		[RegisterProperty]
		public WhatsNewSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with WhatsNewSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class WhatsNewSectionFields : AbstractHierarchicalObject<WhatsNewSectionFields>
		{
			/// <summary>
			/// The content item of type WhatsNewSection that is a target of the extended API.
			/// </summary>
			private readonly WhatsNewSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="WhatsNewSectionFields" /> class with the specified content item of type WhatsNewSection.
			/// </summary>
			/// <param name="instance">The content item of type WhatsNewSection that is a target of the extended API.</param>
			public WhatsNewSectionFields(WhatsNewSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// WhatsNewSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.WhatsNewSectionID;
				}
				set
				{
					mInstance.WhatsNewSectionID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="WhatsNewSection" /> class.
		/// </summary>
		public WhatsNewSection() : base(CLASS_NAME)
		{
			mFields = new WhatsNewSectionFields(this);
		}

		#endregion
	}
}