//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(ApplicationDetails.CLASS_NAME, typeof(ApplicationDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type ApplicationDetails.
	/// </summary>
	public partial class ApplicationDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.ApplicationDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with ApplicationDetails fields.
		/// </summary>
		private readonly ApplicationDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ApplicationDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int ApplicationDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ApplicationDetailsID"), 0);
			}
			set
			{
				SetValue("ApplicationDetailsID", value);
			}
		}


		/// <summary>
		/// Application Number.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ApplicationNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ApplicationNumber"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ApplicationNumber", value);
			}
		}


		/// <summary>
		/// Application Type.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ApplicationType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ApplicationType"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ApplicationType", value);
			}
		}


		/// <summary>
		/// Applicaton Services.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ApplicatonServices
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ApplicatonServices"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ApplicatonServices", value);
			}
		}


		/// <summary>
		/// Application Status.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ApplicationStatus
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ApplicationStatus"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ApplicationStatus", value);
			}
		}


		/// <summary>
		/// Introducer Name.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_IntroducerName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_IntroducerName"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_IntroducerName", value);
			}
		}


		/// <summary>
		/// Introducer CIF.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_IntroducerCIF
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_IntroducerCIF"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_IntroducerCIF", value);
			}
		}


		/// <summary>
		/// Responsible Banking Center.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ResponsibleBankingCenter
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ResponsibleBankingCenter"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ResponsibleBankingCenter", value);
			}
		}


		/// <summary>
		/// Responsible Officer.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ResponsibleOfficer
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ResponsibleOfficer"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ResponsibleOfficer", value);
			}
		}


		/// <summary>
		/// Created By.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_CreatedBy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_CreatedBy"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_CreatedBy", value);
			}
		}


		/// <summary>
		/// Document Submitted By User ID.
		/// </summary>
		[DatabaseField]
		public int ApplicationDetails_DocumentSubmittedByUserID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ApplicationDetails_DocumentSubmittedByUserID"), 0);
			}
			set
			{
				SetValue("ApplicationDetails_DocumentSubmittedByUserID", value);
			}
		}


		/// <summary>
		/// Submitted By.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_SubmittedBy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_SubmittedBy"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_SubmittedBy", value);
			}
		}


		/// <summary>
		/// Submitted On.
		/// </summary>
		[DatabaseField]
		public DateTime ApplicationDetails_SubmittedOn
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ApplicationDetails_SubmittedOn"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ApplicationDetails_SubmittedOn", value);
			}
		}


		/// <summary>
		/// Last Modified By.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_LastModifiedBy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_LastModifiedBy"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_LastModifiedBy", value);
			}
		}


		/// <summary>
		/// Current Stage.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_CurrentStage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_CurrentStage"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_CurrentStage", value);
			}
		}


		/// <summary>
		/// Previous Stage.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_PreviousStage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_PreviousStage"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_PreviousStage", value);
			}
		}


		/// <summary>
		/// Entity .
		/// </summary>
		[DatabaseField]
		public Guid ApplicationDetails_UserOrganisation
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("ApplicationDetails_UserOrganisation"), Guid.Empty);
			}
			set
			{
				SetValue("ApplicationDetails_UserOrganisation", value);
			}
		}


		/// <summary>
		/// Application Last Status.
		/// </summary>
		[DatabaseField]
		public string ApplicationDetails_ApplicationLastStatus
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationDetails_ApplicationLastStatus"), @"");
			}
			set
			{
				SetValue("ApplicationDetails_ApplicationLastStatus", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ApplicationDetails fields.
		/// </summary>
		[RegisterProperty]
		public ApplicationDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ApplicationDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ApplicationDetailsFields : AbstractHierarchicalObject<ApplicationDetailsFields>
		{
			/// <summary>
			/// The content item of type ApplicationDetails that is a target of the extended API.
			/// </summary>
			private readonly ApplicationDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ApplicationDetailsFields" /> class with the specified content item of type ApplicationDetails.
			/// </summary>
			/// <param name="instance">The content item of type ApplicationDetails that is a target of the extended API.</param>
			public ApplicationDetailsFields(ApplicationDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ApplicationDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ApplicationDetailsID;
				}
				set
				{
					mInstance.ApplicationDetailsID = value;
				}
			}


			/// <summary>
			/// Application Number.
			/// </summary>
			public string _ApplicationNumber
			{
				get
				{
					return mInstance.ApplicationDetails_ApplicationNumber;
				}
				set
				{
					mInstance.ApplicationDetails_ApplicationNumber = value;
				}
			}


			/// <summary>
			/// Application Type.
			/// </summary>
			public string _ApplicationType
			{
				get
				{
					return mInstance.ApplicationDetails_ApplicationType;
				}
				set
				{
					mInstance.ApplicationDetails_ApplicationType = value;
				}
			}


			/// <summary>
			/// Applicaton Services.
			/// </summary>
			public string _ApplicatonServices
			{
				get
				{
					return mInstance.ApplicationDetails_ApplicatonServices;
				}
				set
				{
					mInstance.ApplicationDetails_ApplicatonServices = value;
				}
			}


			/// <summary>
			/// Application Status.
			/// </summary>
			public string _ApplicationStatus
			{
				get
				{
					return mInstance.ApplicationDetails_ApplicationStatus;
				}
				set
				{
					mInstance.ApplicationDetails_ApplicationStatus = value;
				}
			}


			/// <summary>
			/// Introducer Name.
			/// </summary>
			public string _IntroducerName
			{
				get
				{
					return mInstance.ApplicationDetails_IntroducerName;
				}
				set
				{
					mInstance.ApplicationDetails_IntroducerName = value;
				}
			}


			/// <summary>
			/// Introducer CIF.
			/// </summary>
			public string _IntroducerCIF
			{
				get
				{
					return mInstance.ApplicationDetails_IntroducerCIF;
				}
				set
				{
					mInstance.ApplicationDetails_IntroducerCIF = value;
				}
			}


			/// <summary>
			/// Responsible Banking Center.
			/// </summary>
			public string _ResponsibleBankingCenter
			{
				get
				{
					return mInstance.ApplicationDetails_ResponsibleBankingCenter;
				}
				set
				{
					mInstance.ApplicationDetails_ResponsibleBankingCenter = value;
				}
			}


			/// <summary>
			/// Responsible Officer.
			/// </summary>
			public string _ResponsibleOfficer
			{
				get
				{
					return mInstance.ApplicationDetails_ResponsibleOfficer;
				}
				set
				{
					mInstance.ApplicationDetails_ResponsibleOfficer = value;
				}
			}


			/// <summary>
			/// Created By.
			/// </summary>
			public string _CreatedBy
			{
				get
				{
					return mInstance.ApplicationDetails_CreatedBy;
				}
				set
				{
					mInstance.ApplicationDetails_CreatedBy = value;
				}
			}


			/// <summary>
			/// Document Submitted By User ID.
			/// </summary>
			public int _DocumentSubmittedByUserID
			{
				get
				{
					return mInstance.ApplicationDetails_DocumentSubmittedByUserID;
				}
				set
				{
					mInstance.ApplicationDetails_DocumentSubmittedByUserID = value;
				}
			}


			/// <summary>
			/// Submitted By.
			/// </summary>
			public string _SubmittedBy
			{
				get
				{
					return mInstance.ApplicationDetails_SubmittedBy;
				}
				set
				{
					mInstance.ApplicationDetails_SubmittedBy = value;
				}
			}


			/// <summary>
			/// Submitted On.
			/// </summary>
			public DateTime _SubmittedOn
			{
				get
				{
					return mInstance.ApplicationDetails_SubmittedOn;
				}
				set
				{
					mInstance.ApplicationDetails_SubmittedOn = value;
				}
			}


			/// <summary>
			/// Last Modified By.
			/// </summary>
			public string _LastModifiedBy
			{
				get
				{
					return mInstance.ApplicationDetails_LastModifiedBy;
				}
				set
				{
					mInstance.ApplicationDetails_LastModifiedBy = value;
				}
			}


			/// <summary>
			/// Current Stage.
			/// </summary>
			public string _CurrentStage
			{
				get
				{
					return mInstance.ApplicationDetails_CurrentStage;
				}
				set
				{
					mInstance.ApplicationDetails_CurrentStage = value;
				}
			}


			/// <summary>
			/// Previous Stage.
			/// </summary>
			public string _PreviousStage
			{
				get
				{
					return mInstance.ApplicationDetails_PreviousStage;
				}
				set
				{
					mInstance.ApplicationDetails_PreviousStage = value;
				}
			}


			/// <summary>
			/// Entity .
			/// </summary>
			public Guid _UserOrganisation
			{
				get
				{
					return mInstance.ApplicationDetails_UserOrganisation;
				}
				set
				{
					mInstance.ApplicationDetails_UserOrganisation = value;
				}
			}


			/// <summary>
			/// Application Last Status.
			/// </summary>
			public string _ApplicationLastStatus
			{
				get
				{
					return mInstance.ApplicationDetails_ApplicationLastStatus;
				}
				set
				{
					mInstance.ApplicationDetails_ApplicationLastStatus = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ApplicationDetails" /> class.
		/// </summary>
		public ApplicationDetails() : base(CLASS_NAME)
		{
			mFields = new ApplicationDetailsFields(this);
		}

		#endregion
	}
}