//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(Applications.CLASS_NAME, typeof(Applications))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type Applications.
	/// </summary>
	public partial class Applications : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.Applications";


		/// <summary>
		/// The instance of the class that provides extended API for working with Applications fields.
		/// </summary>
		private readonly ApplicationsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ApplicationsID.
		/// </summary>
		[DatabaseIDField]
		public int ApplicationsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ApplicationsID"), 0);
			}
			set
			{
				SetValue("ApplicationsID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Applications fields.
		/// </summary>
		[RegisterProperty]
		public ApplicationsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Applications fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ApplicationsFields : AbstractHierarchicalObject<ApplicationsFields>
		{
			/// <summary>
			/// The content item of type Applications that is a target of the extended API.
			/// </summary>
			private readonly Applications mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ApplicationsFields" /> class with the specified content item of type Applications.
			/// </summary>
			/// <param name="instance">The content item of type Applications that is a target of the extended API.</param>
			public ApplicationsFields(Applications instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ApplicationsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ApplicationsID;
				}
				set
				{
					mInstance.ApplicationsID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Applications" /> class.
		/// </summary>
		public Applications() : base(CLASS_NAME)
		{
			mFields = new ApplicationsFields(this);
		}

		#endregion
	}
}