//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(CompanyBusinessProfile.CLASS_NAME, typeof(CompanyBusinessProfile))]

namespace CMS.DocumentEngine.Types.Eurobank
{
    /// <summary>
    /// Represents a content item of type CompanyBusinessProfile.
    /// </summary>
    public partial class CompanyBusinessProfile : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "Eurobank.CompanyBusinessProfile";


        /// <summary>
        /// The instance of the class that provides extended API for working with CompanyBusinessProfile fields.
        /// </summary>
        private readonly CompanyBusinessProfileFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// CompanyBusinessProfileID.
        /// </summary>
        [DatabaseIDField]
        public int CompanyBusinessProfileID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CompanyBusinessProfileID"), 0);
            }
            set
            {
                SetValue("CompanyBusinessProfileID", value);
            }
        }


        /// <summary>
        /// Sponsoring Entity Name.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_SponsoringEntityName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_SponsoringEntityName"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_SponsoringEntityName", value);
            }
        }


        /// <summary>
        /// Line Of Business Of The Sponsoring Entity.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_LineOfBusinessOfTheSponsoringEntity
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_LineOfBusinessOfTheSponsoringEntity"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_LineOfBusinessOfTheSponsoringEntity", value);
            }
        }


        /// <summary>
        /// Website Of The Sponsoring Entity.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_WebsiteOfTheSponsoringEntity
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_WebsiteOfTheSponsoringEntity"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_WebsiteOfTheSponsoringEntity", value);
            }
        }


        /// <summary>
        /// Main Business Activities.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_MainBusinessActivities
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_MainBusinessActivities"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_MainBusinessActivities", value);
            }
        }


        /// <summary>
        /// Number of Years in Operation.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_NumberofYearsinOperation
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_NumberofYearsinOperation"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_NumberofYearsinOperation", value);
            }
        }


        /// <summary>
        /// Number of Employes.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_NumberofEmployes
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_NumberofEmployes"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_NumberofEmployes", value);
            }
        }


        /// <summary>
        /// Website Address.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_WebsiteAddress
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_WebsiteAddress"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_WebsiteAddress", value);
            }
        }


        /// <summary>
        /// Corporation is engaged in the provision of financial and investment services.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_Corporationisengagedintheprovisionoffinancialandinvestmentservices
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_Corporationisengagedintheprovisionoffinancialandinvestmentservices"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_Corporationisengagedintheprovisionoffinancialandinvestmentservices", value);
            }
        }


        /// <summary>
        /// Issuing Authority.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_IssuingAuthority
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_IssuingAuthority"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_IssuingAuthority", value);
            }
        }


        /// <summary>
        /// Economic Sector / Industry.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_EconomicSectorIndustry
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_EconomicSectorIndustry"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_EconomicSectorIndustry", value);
            }
        }


        /// <summary>
        /// Country of Origin of Wealth / Activities.
        /// </summary>
        [DatabaseField]
        public string CompanyBusinessProfile_CountryofOriginofWealthActivities
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyBusinessProfile_CountryofOriginofWealthActivities"), @"");
            }
            set
            {
                SetValue("CompanyBusinessProfile_CountryofOriginofWealthActivities", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CompanyBusinessProfile fields.
        /// </summary>
        [RegisterProperty]
        public CompanyBusinessProfileFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CompanyBusinessProfile fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CompanyBusinessProfileFields : AbstractHierarchicalObject<CompanyBusinessProfileFields>
        {
            /// <summary>
            /// The content item of type CompanyBusinessProfile that is a target of the extended API.
            /// </summary>
            private readonly CompanyBusinessProfile mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CompanyBusinessProfileFields" /> class with the specified content item of type CompanyBusinessProfile.
            /// </summary>
            /// <param name="instance">The content item of type CompanyBusinessProfile that is a target of the extended API.</param>
            public CompanyBusinessProfileFields(CompanyBusinessProfile instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// CompanyBusinessProfileID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.CompanyBusinessProfileID;
                }
                set
                {
                    mInstance.CompanyBusinessProfileID = value;
                }
            }


            /// <summary>
            /// Sponsoring Entity Name.
            /// </summary>
            public string _SponsoringEntityName
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_SponsoringEntityName;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_SponsoringEntityName = value;
                }
            }


            /// <summary>
            /// Line Of Business Of The Sponsoring Entity.
            /// </summary>
            public string _LineOfBusinessOfTheSponsoringEntity
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_LineOfBusinessOfTheSponsoringEntity;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_LineOfBusinessOfTheSponsoringEntity = value;
                }
            }


            /// <summary>
            /// Website Of The Sponsoring Entity.
            /// </summary>
            public string _WebsiteOfTheSponsoringEntity
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_WebsiteOfTheSponsoringEntity;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_WebsiteOfTheSponsoringEntity = value;
                }
            }


            /// <summary>
            /// Main Business Activities.
            /// </summary>
            public string _MainBusinessActivities
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_MainBusinessActivities;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_MainBusinessActivities = value;
                }
            }


            /// <summary>
            /// Number of Years in Operation.
            /// </summary>
            public string _NumberofYearsinOperation
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_NumberofYearsinOperation;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_NumberofYearsinOperation = value;
                }
            }


            /// <summary>
            /// Number of Employes.
            /// </summary>
            public string _NumberofEmployes
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_NumberofEmployes;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_NumberofEmployes = value;
                }
            }


            /// <summary>
            /// Website Address.
            /// </summary>
            public string _WebsiteAddress
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_WebsiteAddress;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_WebsiteAddress = value;
                }
            }


            /// <summary>
            /// Corporation is engaged in the provision of financial and investment services.
            /// </summary>
            public string _Corporationisengagedintheprovisionoffinancialandinvestmentservices
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_Corporationisengagedintheprovisionoffinancialandinvestmentservices;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_Corporationisengagedintheprovisionoffinancialandinvestmentservices = value;
                }
            }


            /// <summary>
            /// Issuing Authority.
            /// </summary>
            public string _IssuingAuthority
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_IssuingAuthority;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_IssuingAuthority = value;
                }
            }


            /// <summary>
            /// Economic Sector / Industry.
            /// </summary>
            public string _EconomicSectorIndustry
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_EconomicSectorIndustry;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_EconomicSectorIndustry = value;
                }
            }


            /// <summary>
            /// Country of Origin of Wealth / Activities.
            /// </summary>
            public string _CountryofOriginofWealthActivities
            {
                get
                {
                    return mInstance.CompanyBusinessProfile_CountryofOriginofWealthActivities;
                }
                set
                {
                    mInstance.CompanyBusinessProfile_CountryofOriginofWealthActivities = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyBusinessProfile" /> class.
        /// </summary>
        public CompanyBusinessProfile() : base(CLASS_NAME)
        {
            mFields = new CompanyBusinessProfileFields(this);
        }

        #endregion
    }
}