//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(CompanyGroupStructure.CLASS_NAME, typeof(CompanyGroupStructure))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type CompanyGroupStructure.
	/// </summary>
	public partial class CompanyGroupStructure : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.CompanyGroupStructure";


		/// <summary>
		/// The instance of the class that provides extended API for working with CompanyGroupStructure fields.
		/// </summary>
		private readonly CompanyGroupStructureFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// GroupStructureID.
		/// </summary>
		[DatabaseIDField]
		public int GroupStructureID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GroupStructureID"), 0);
			}
			set
			{
				SetValue("GroupStructureID", value);
			}
		}


		/// <summary>
		/// Entity Type.
		/// </summary>
		[DatabaseField]
		public string CompanyGroupStructure_EntityType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyGroupStructure_EntityType"), @"");
			}
			set
			{
				SetValue("CompanyGroupStructure_EntityType", value);
			}
		}


		/// <summary>
		/// Entity Name.
		/// </summary>
		[DatabaseField]
		public string CompanyGroupStructure_EntityName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyGroupStructure_EntityName"), @"");
			}
			set
			{
				SetValue("CompanyGroupStructure_EntityName", value);
			}
		}


		/// <summary>
		/// Parent.
		/// </summary>
		[DatabaseField]
		public string CompanyGroupStructure_Parent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyGroupStructure_Parent"), @"");
			}
			set
			{
				SetValue("CompanyGroupStructure_Parent", value);
			}
		}


		/// <summary>
		/// Business Activities.
		/// </summary>
		[DatabaseField]
		public string CompanyGroupStructure_BusinessActivities
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyGroupStructure_BusinessActivities"), @"");
			}
			set
			{
				SetValue("CompanyGroupStructure_BusinessActivities", value);
			}
		}


		/// <summary>
		/// Is Confirmed.
		/// </summary>
		[DatabaseField]
		public bool Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Status"), false);
			}
			set
			{
				SetValue("Status", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CompanyGroupStructure fields.
		/// </summary>
		[RegisterProperty]
		public CompanyGroupStructureFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CompanyGroupStructure fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CompanyGroupStructureFields : AbstractHierarchicalObject<CompanyGroupStructureFields>
		{
			/// <summary>
			/// The content item of type CompanyGroupStructure that is a target of the extended API.
			/// </summary>
			private readonly CompanyGroupStructure mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CompanyGroupStructureFields" /> class with the specified content item of type CompanyGroupStructure.
			/// </summary>
			/// <param name="instance">The content item of type CompanyGroupStructure that is a target of the extended API.</param>
			public CompanyGroupStructureFields(CompanyGroupStructure instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// GroupStructureID.
			/// </summary>
			public int GroupStructureID
			{
				get
				{
					return mInstance.GroupStructureID;
				}
				set
				{
					mInstance.GroupStructureID = value;
				}
			}


			/// <summary>
			/// Entity Type.
			/// </summary>
			public string _EntityType
			{
				get
				{
					return mInstance.CompanyGroupStructure_EntityType;
				}
				set
				{
					mInstance.CompanyGroupStructure_EntityType = value;
				}
			}


			/// <summary>
			/// Entity Name.
			/// </summary>
			public string _EntityName
			{
				get
				{
					return mInstance.CompanyGroupStructure_EntityName;
				}
				set
				{
					mInstance.CompanyGroupStructure_EntityName = value;
				}
			}


			/// <summary>
			/// Parent.
			/// </summary>
			public string _Parent
			{
				get
				{
					return mInstance.CompanyGroupStructure_Parent;
				}
				set
				{
					mInstance.CompanyGroupStructure_Parent = value;
				}
			}


			/// <summary>
			/// Business Activities.
			/// </summary>
			public string _BusinessActivities
			{
				get
				{
					return mInstance.CompanyGroupStructure_BusinessActivities;
				}
				set
				{
					mInstance.CompanyGroupStructure_BusinessActivities = value;
				}
			}


			/// <summary>
			/// Is Confirmed.
			/// </summary>
			public bool Status
			{
				get
				{
					return mInstance.Status;
				}
				set
				{
					mInstance.Status = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CompanyGroupStructure" /> class.
		/// </summary>
		public CompanyGroupStructure() : base(CLASS_NAME)
		{
			mFields = new CompanyGroupStructureFields(this);
		}

		#endregion
	}
}