//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(TermsAndCondition.CLASS_NAME, typeof(TermsAndCondition))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type TermsAndCondition.
	/// </summary>
	public partial class TermsAndCondition : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.TermsAndCondition";


		/// <summary>
		/// The instance of the class that provides extended API for working with TermsAndCondition fields.
		/// </summary>
		private readonly TermsAndConditionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TermsAndConditionID.
		/// </summary>
		[DatabaseIDField]
		public int TermsAndConditionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TermsAndConditionID"), 0);
			}
			set
			{
				SetValue("TermsAndConditionID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Teaser.
		/// </summary>
		[DatabaseField]
		public string BannerImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerImage"), "");
			}
			set
			{
				SetValue("BannerImage", value);
			}
		}


		/// <summary>
		/// Content.
		/// </summary>
		[DatabaseField]
		public string Content
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Content"), @"");
			}
			set
			{
				SetValue("Content", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TermsAndCondition fields.
		/// </summary>
		[RegisterProperty]
		public TermsAndConditionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TermsAndCondition fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TermsAndConditionFields : AbstractHierarchicalObject<TermsAndConditionFields>
		{
			/// <summary>
			/// The content item of type TermsAndCondition that is a target of the extended API.
			/// </summary>
			private readonly TermsAndCondition mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TermsAndConditionFields" /> class with the specified content item of type TermsAndCondition.
			/// </summary>
			/// <param name="instance">The content item of type TermsAndCondition that is a target of the extended API.</param>
			public TermsAndConditionFields(TermsAndCondition instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TermsAndConditionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TermsAndConditionID;
				}
				set
				{
					mInstance.TermsAndConditionID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Teaser.
			/// </summary>
			public IEnumerable<DocumentAttachment> BannerImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachments("BannerImage");
				}
			}


			/// <summary>
			/// Content.
			/// </summary>
			public string Content
			{
				get
				{
					return mInstance.Content;
				}
				set
				{
					mInstance.Content = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TermsAndCondition" /> class.
		/// </summary>
		public TermsAndCondition() : base(CLASS_NAME)
		{
			mFields = new TermsAndConditionFields(this);
		}

		#endregion
	}
}