//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(DebitCardDetails.CLASS_NAME, typeof(DebitCardDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type DebitCardDetails.
	/// </summary>
	public partial class DebitCardDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.DebitCardDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with DebitCardDetails fields.
		/// </summary>
		private readonly DebitCardDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DebitCardDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int DebitCardDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DebitCardDetailsID"), 0);
			}
			set
			{
				SetValue("DebitCardDetailsID", value);
			}
		}


		/// <summary>
		/// Collected By Name.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_CollectedByName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_CollectedByName"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_CollectedByName", value);
			}
		}


		/// <summary>
		/// Account.
		/// </summary>
		[DatabaseField]
		public string AssociatedAccount
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AssociatedAccount"), @"");
			}
			set
			{
				SetValue("AssociatedAccount", value);
			}
		}


		/// <summary>
		/// Card Type.
		/// </summary>
		[DatabaseField]
		public Guid DebitCardDetails_CardType
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("DebitCardDetails_CardType"), Guid.Empty);
			}
			set
			{
				SetValue("DebitCardDetails_CardType", value);
			}
		}


		/// <summary>
		/// Card Holder Name.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_CardholderName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_CardholderName"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_CardholderName", value);
			}
		}


		/// <summary>
		/// Card Holder Identity Number.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_CardHolderIdentityNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_CardHolderIdentityNumber"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_CardHolderIdentityNumber", value);
			}
		}


		/// <summary>
		/// Country Of Issue.
		/// </summary>
		[DatabaseField]
		public int DebitCardDetails_CardHolderCountryOfIssue
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DebitCardDetails_CardHolderCountryOfIssue"), 0);
			}
			set
			{
				SetValue("DebitCardDetails_CardHolderCountryOfIssue", value);
			}
		}


		/// <summary>
		/// Full Name as it will appear on card.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_FullName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_FullName"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_FullName", value);
			}
		}


		/// <summary>
		/// Mobile for SMS Alerts.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_MobileNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_MobileNumber"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_MobileNumber", value);
			}
		}


		/// <summary>
		/// Country Code.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_MobileNumber_CountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_MobileNumber_CountryCode"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_MobileNumber_CountryCode", value);
			}
		}


		/// <summary>
		/// Company's Name as it will appear on Card.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_CompanyNameAppearOnCard
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_CompanyNameAppearOnCard"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_CompanyNameAppearOnCard", value);
			}
		}


		/// <summary>
		/// Dispatch Method of the card.
		/// </summary>
		[DatabaseField]
		public Guid DebitCardDetails_DispatchMethod
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("DebitCardDetails_DispatchMethod"), Guid.Empty);
			}
			set
			{
				SetValue("DebitCardDetails_DispatchMethod", value);
			}
		}


		/// <summary>
		/// Delivery Address.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_DeliveryAddress
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_DeliveryAddress"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_DeliveryAddress", value);
			}
		}


		/// <summary>
		/// Other Delivery Address.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_OtherDeliveryAddress
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_OtherDeliveryAddress"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_OtherDeliveryAddress", value);
			}
		}


		/// <summary>
		/// Collected By.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_CollectedBy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_CollectedBy"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_CollectedBy", value);
			}
		}


		/// <summary>
		/// Identity / Passport Number.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_IdentityNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_IdentityNumber"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_IdentityNumber", value);
			}
		}


		/// <summary>
		/// DebitCard Details Status.
		/// </summary>
		[DatabaseField]
		public bool DebitCardDetails_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("DebitCardDetails_Status"), false);
			}
			set
			{
				SetValue("DebitCardDetails_Status", value);
			}
		}


		/// <summary>
		/// Delivery Details.
		/// </summary>
		[DatabaseField]
		public string DebitCardDetails_DeliveryDetails
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DebitCardDetails_DeliveryDetails"), @"");
			}
			set
			{
				SetValue("DebitCardDetails_DeliveryDetails", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DebitCardDetails fields.
		/// </summary>
		[RegisterProperty]
		public DebitCardDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DebitCardDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DebitCardDetailsFields : AbstractHierarchicalObject<DebitCardDetailsFields>
		{
			/// <summary>
			/// The content item of type DebitCardDetails that is a target of the extended API.
			/// </summary>
			private readonly DebitCardDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DebitCardDetailsFields" /> class with the specified content item of type DebitCardDetails.
			/// </summary>
			/// <param name="instance">The content item of type DebitCardDetails that is a target of the extended API.</param>
			public DebitCardDetailsFields(DebitCardDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DebitCardDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DebitCardDetailsID;
				}
				set
				{
					mInstance.DebitCardDetailsID = value;
				}
			}


			/// <summary>
			/// Collected By Name.
			/// </summary>
			public string _CollectedByName
			{
				get
				{
					return mInstance.DebitCardDetails_CollectedByName;
				}
				set
				{
					mInstance.DebitCardDetails_CollectedByName = value;
				}
			}


			/// <summary>
			/// Account.
			/// </summary>
			public string AssociatedAccount
			{
				get
				{
					return mInstance.AssociatedAccount;
				}
				set
				{
					mInstance.AssociatedAccount = value;
				}
			}


			/// <summary>
			/// Card Type.
			/// </summary>
			public Guid _CardType
			{
				get
				{
					return mInstance.DebitCardDetails_CardType;
				}
				set
				{
					mInstance.DebitCardDetails_CardType = value;
				}
			}


			/// <summary>
			/// Card Holder Name.
			/// </summary>
			public string _CardholderName
			{
				get
				{
					return mInstance.DebitCardDetails_CardholderName;
				}
				set
				{
					mInstance.DebitCardDetails_CardholderName = value;
				}
			}


			/// <summary>
			/// Card Holder Identity Number.
			/// </summary>
			public string _CardHolderIdentityNumber
			{
				get
				{
					return mInstance.DebitCardDetails_CardHolderIdentityNumber;
				}
				set
				{
					mInstance.DebitCardDetails_CardHolderIdentityNumber = value;
				}
			}


			/// <summary>
			/// Country Of Issue.
			/// </summary>
			public int _CardHolderCountryOfIssue
			{
				get
				{
					return mInstance.DebitCardDetails_CardHolderCountryOfIssue;
				}
				set
				{
					mInstance.DebitCardDetails_CardHolderCountryOfIssue = value;
				}
			}


			/// <summary>
			/// Full Name as it will appear on card.
			/// </summary>
			public string _FullName
			{
				get
				{
					return mInstance.DebitCardDetails_FullName;
				}
				set
				{
					mInstance.DebitCardDetails_FullName = value;
				}
			}


			/// <summary>
			/// Mobile for SMS Alerts.
			/// </summary>
			public string _MobileNumber
			{
				get
				{
					return mInstance.DebitCardDetails_MobileNumber;
				}
				set
				{
					mInstance.DebitCardDetails_MobileNumber = value;
				}
			}


			/// <summary>
			/// Country Code.
			/// </summary>
			public string _MobileNumber_CountryCode
			{
				get
				{
					return mInstance.DebitCardDetails_MobileNumber_CountryCode;
				}
				set
				{
					mInstance.DebitCardDetails_MobileNumber_CountryCode = value;
				}
			}


			/// <summary>
			/// Company's Name as it will appear on Card.
			/// </summary>
			public string _CompanyNameAppearOnCard
			{
				get
				{
					return mInstance.DebitCardDetails_CompanyNameAppearOnCard;
				}
				set
				{
					mInstance.DebitCardDetails_CompanyNameAppearOnCard = value;
				}
			}


			/// <summary>
			/// Dispatch Method of the card.
			/// </summary>
			public Guid _DispatchMethod
			{
				get
				{
					return mInstance.DebitCardDetails_DispatchMethod;
				}
				set
				{
					mInstance.DebitCardDetails_DispatchMethod = value;
				}
			}


			/// <summary>
			/// Delivery Address.
			/// </summary>
			public string _DeliveryAddress
			{
				get
				{
					return mInstance.DebitCardDetails_DeliveryAddress;
				}
				set
				{
					mInstance.DebitCardDetails_DeliveryAddress = value;
				}
			}


			/// <summary>
			/// Other Delivery Address.
			/// </summary>
			public string _OtherDeliveryAddress
			{
				get
				{
					return mInstance.DebitCardDetails_OtherDeliveryAddress;
				}
				set
				{
					mInstance.DebitCardDetails_OtherDeliveryAddress = value;
				}
			}


			/// <summary>
			/// Collected By.
			/// </summary>
			public string _CollectedBy
			{
				get
				{
					return mInstance.DebitCardDetails_CollectedBy;
				}
				set
				{
					mInstance.DebitCardDetails_CollectedBy = value;
				}
			}


			/// <summary>
			/// Identity / Passport Number.
			/// </summary>
			public string _IdentityNumber
			{
				get
				{
					return mInstance.DebitCardDetails_IdentityNumber;
				}
				set
				{
					mInstance.DebitCardDetails_IdentityNumber = value;
				}
			}


			/// <summary>
			/// DebitCard Details Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.DebitCardDetails_Status;
				}
				set
				{
					mInstance.DebitCardDetails_Status = value;
				}
			}


			/// <summary>
			/// Delivery Details.
			/// </summary>
			public string _DeliveryDetails
			{
				get
				{
					return mInstance.DebitCardDetails_DeliveryDetails;
				}
				set
				{
					mInstance.DebitCardDetails_DeliveryDetails = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DebitCardDetails" /> class.
		/// </summary>
		public DebitCardDetails() : base(CLASS_NAME)
		{
			mFields = new DebitCardDetailsFields(this);
		}

		#endregion
	}
}