//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(PepAssociates.CLASS_NAME, typeof(PepAssociates))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type PepAssociates.
	/// </summary>
	public partial class PepAssociates : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.PepAssociates";


		/// <summary>
		/// The instance of the class that provides extended API for working with PepAssociates fields.
		/// </summary>
		private readonly PepAssociatesFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PepAssociatesID.
		/// </summary>
		[DatabaseIDField]
		public int PepAssociatesID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PepAssociatesID"), 0);
			}
			set
			{
				SetValue("PepAssociatesID", value);
			}
		}


		/// <summary>
		/// First Name.
		/// </summary>
		[DatabaseField]
		public string PepAssociates_FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PepAssociates_FirstName"), @"");
			}
			set
			{
				SetValue("PepAssociates_FirstName", value);
			}
		}


		/// <summary>
		/// Surname.
		/// </summary>
		[DatabaseField]
		public string PepAssociates_Surname
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PepAssociates_Surname"), @"");
			}
			set
			{
				SetValue("PepAssociates_Surname", value);
			}
		}


		/// <summary>
		/// Relationship.
		/// </summary>
		[DatabaseField]
		public Guid PepAssociates_Relationship
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("PepAssociates_Relationship"), Guid.Empty);
			}
			set
			{
				SetValue("PepAssociates_Relationship", value);
			}
		}


		/// <summary>
		/// Position/Organization.
		/// </summary>
		[DatabaseField]
		public string PepAssociates_PositionOrganization
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PepAssociates_PositionOrganization"), @"");
			}
			set
			{
				SetValue("PepAssociates_PositionOrganization", value);
			}
		}


		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public int PepAssociates_Country
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PepAssociates_Country"), 0);
			}
			set
			{
				SetValue("PepAssociates_Country", value);
			}
		}


		/// <summary>
		/// Since.
		/// </summary>
		[DatabaseField]
		public DateTime PepAssociates_Since
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("PepAssociates_Since"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("PepAssociates_Since", value);
			}
		}


		/// <summary>
		/// Until.
		/// </summary>
		[DatabaseField]
		public DateTime PepAssociates_Until
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("PepAssociates_Until"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("PepAssociates_Until", value);
			}
		}


		/// <summary>
		/// Associates.
		/// </summary>
		[DatabaseField]
		public bool PepAssociates_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("PepAssociates_Status"), false);
			}
			set
			{
				SetValue("PepAssociates_Status", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PepAssociates fields.
		/// </summary>
		[RegisterProperty]
		public PepAssociatesFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PepAssociates fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PepAssociatesFields : AbstractHierarchicalObject<PepAssociatesFields>
		{
			/// <summary>
			/// The content item of type PepAssociates that is a target of the extended API.
			/// </summary>
			private readonly PepAssociates mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PepAssociatesFields" /> class with the specified content item of type PepAssociates.
			/// </summary>
			/// <param name="instance">The content item of type PepAssociates that is a target of the extended API.</param>
			public PepAssociatesFields(PepAssociates instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PepAssociatesID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PepAssociatesID;
				}
				set
				{
					mInstance.PepAssociatesID = value;
				}
			}


			/// <summary>
			/// First Name.
			/// </summary>
			public string _FirstName
			{
				get
				{
					return mInstance.PepAssociates_FirstName;
				}
				set
				{
					mInstance.PepAssociates_FirstName = value;
				}
			}


			/// <summary>
			/// Surname.
			/// </summary>
			public string _Surname
			{
				get
				{
					return mInstance.PepAssociates_Surname;
				}
				set
				{
					mInstance.PepAssociates_Surname = value;
				}
			}


			/// <summary>
			/// Relationship.
			/// </summary>
			public Guid _Relationship
			{
				get
				{
					return mInstance.PepAssociates_Relationship;
				}
				set
				{
					mInstance.PepAssociates_Relationship = value;
				}
			}


			/// <summary>
			/// Position/Organization.
			/// </summary>
			public string _PositionOrganization
			{
				get
				{
					return mInstance.PepAssociates_PositionOrganization;
				}
				set
				{
					mInstance.PepAssociates_PositionOrganization = value;
				}
			}


			/// <summary>
			/// Country.
			/// </summary>
			public int _Country
			{
				get
				{
					return mInstance.PepAssociates_Country;
				}
				set
				{
					mInstance.PepAssociates_Country = value;
				}
			}


			/// <summary>
			/// Since.
			/// </summary>
			public DateTime _Since
			{
				get
				{
					return mInstance.PepAssociates_Since;
				}
				set
				{
					mInstance.PepAssociates_Since = value;
				}
			}


			/// <summary>
			/// Until.
			/// </summary>
			public DateTime _Until
			{
				get
				{
					return mInstance.PepAssociates_Until;
				}
				set
				{
					mInstance.PepAssociates_Until = value;
				}
			}


			/// <summary>
			/// Associates.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.PepAssociates_Status;
				}
				set
				{
					mInstance.PepAssociates_Status = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PepAssociates" /> class.
		/// </summary>
		public PepAssociates() : base(CLASS_NAME)
		{
			mFields = new PepAssociatesFields(this);
		}

		#endregion
	}
}