//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(PepApplicant.CLASS_NAME, typeof(PepApplicant))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type PepApplicant.
	/// </summary>
	public partial class PepApplicant : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.PepApplicant";


		/// <summary>
		/// The instance of the class that provides extended API for working with PepApplicant fields.
		/// </summary>
		private readonly PepApplicantFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PepApplicantID.
		/// </summary>
		[DatabaseIDField]
		public int PepApplicantID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PepApplicantID"), 0);
			}
			set
			{
				SetValue("PepApplicantID", value);
			}
		}


		/// <summary>
		/// Position/Organization.
		/// </summary>
		[DatabaseField]
		public string PepApplicant_PositionOrganization
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PepApplicant_PositionOrganization"), @"");
			}
			set
			{
				SetValue("PepApplicant_PositionOrganization", value);
			}
		}


		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public int PepApplicant_Country
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PepApplicant_Country"), 0);
			}
			set
			{
				SetValue("PepApplicant_Country", value);
			}
		}


		/// <summary>
		/// Since.
		/// </summary>
		[DatabaseField]
		public DateTime PepApplicant_Since
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("PepApplicant_Since"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("PepApplicant_Since", value);
			}
		}


		/// <summary>
		/// Name of PEP.
		/// </summary>
		[DatabaseField]
		public string PepApplicant_FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PepApplicant_FirstName"), @"");
			}
			set
			{
				SetValue("PepApplicant_FirstName", value);
			}
		}


		/// <summary>
		/// Surname of PEP.
		/// </summary>
		[DatabaseField]
		public string PepApplicant_Surname
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PepApplicant_Surname"), @"");
			}
			set
			{
				SetValue("PepApplicant_Surname", value);
			}
		}


		/// <summary>
		/// Until.
		/// </summary>
		[DatabaseField]
		public DateTime PepApplicant_Untill
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("PepApplicant_Untill"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("PepApplicant_Untill", value);
			}
		}


		/// <summary>
		/// Status.
		/// </summary>
		[DatabaseField]
		public bool PepApplicant_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("PepApplicant_Status"), false);
			}
			set
			{
				SetValue("PepApplicant_Status", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PepApplicant fields.
		/// </summary>
		[RegisterProperty]
		public PepApplicantFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PepApplicant fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PepApplicantFields : AbstractHierarchicalObject<PepApplicantFields>
		{
			/// <summary>
			/// The content item of type PepApplicant that is a target of the extended API.
			/// </summary>
			private readonly PepApplicant mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PepApplicantFields" /> class with the specified content item of type PepApplicant.
			/// </summary>
			/// <param name="instance">The content item of type PepApplicant that is a target of the extended API.</param>
			public PepApplicantFields(PepApplicant instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PepApplicantID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PepApplicantID;
				}
				set
				{
					mInstance.PepApplicantID = value;
				}
			}


			/// <summary>
			/// Position/Organization.
			/// </summary>
			public string _PositionOrganization
			{
				get
				{
					return mInstance.PepApplicant_PositionOrganization;
				}
				set
				{
					mInstance.PepApplicant_PositionOrganization = value;
				}
			}


			/// <summary>
			/// Country.
			/// </summary>
			public int _Country
			{
				get
				{
					return mInstance.PepApplicant_Country;
				}
				set
				{
					mInstance.PepApplicant_Country = value;
				}
			}


			/// <summary>
			/// Since.
			/// </summary>
			public DateTime _Since
			{
				get
				{
					return mInstance.PepApplicant_Since;
				}
				set
				{
					mInstance.PepApplicant_Since = value;
				}
			}


			/// <summary>
			/// Name of PEP.
			/// </summary>
			public string _FirstName
			{
				get
				{
					return mInstance.PepApplicant_FirstName;
				}
				set
				{
					mInstance.PepApplicant_FirstName = value;
				}
			}


			/// <summary>
			/// Surname of PEP.
			/// </summary>
			public string _Surname
			{
				get
				{
					return mInstance.PepApplicant_Surname;
				}
				set
				{
					mInstance.PepApplicant_Surname = value;
				}
			}


			/// <summary>
			/// Until.
			/// </summary>
			public DateTime _Untill
			{
				get
				{
					return mInstance.PepApplicant_Untill;
				}
				set
				{
					mInstance.PepApplicant_Untill = value;
				}
			}


			/// <summary>
			/// Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.PepApplicant_Status;
				}
				set
				{
					mInstance.PepApplicant_Status = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PepApplicant" /> class.
		/// </summary>
		public PepApplicant() : base(CLASS_NAME)
		{
			mFields = new PepApplicantFields(this);
		}

		#endregion
	}
}