//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(ContactDetails.CLASS_NAME, typeof(ContactDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type ContactDetails.
	/// </summary>
	public partial class ContactDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.ContactDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactDetails fields.
		/// </summary>
		private readonly ContactDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int ContactDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactDetailsID"), 0);
			}
			set
			{
				SetValue("ContactDetailsID", value);
			}
		}


		/// <summary>
		/// Mobile Country Code.
		/// </summary>
		[DatabaseField]
		public string ContactDetails_Mobile_CountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_Mobile_CountryCode"), @"");
			}
			set
			{
				SetValue("ContactDetails_Mobile_CountryCode", value);
			}
		}


		/// <summary>
		/// Home Country Code.
		/// </summary>
		[DatabaseField]
		public string ContactDetails_Home_CountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_Home_CountryCode"), @"");
			}
			set
			{
				SetValue("ContactDetails_Home_CountryCode", value);
			}
		}


		/// <summary>
		/// Work Country Code.
		/// </summary>
		[DatabaseField]
		public string ContactDetails_Work_CountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_Work_CountryCode"), @"");
			}
			set
			{
				SetValue("ContactDetails_Work_CountryCode", value);
			}
		}


		/// <summary>
		/// Fax Country Code.
		/// </summary>
		[DatabaseField]
		public string ContactDetails_Fax_CountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_Fax_CountryCode"), @"");
			}
			set
			{
				SetValue("ContactDetails_Fax_CountryCode", value);
			}
		}


		/// <summary>
		/// Mobile Tel. No. (Incl. country code).
		/// </summary>
		[DatabaseField]
		public string ContactDetails_MobileTelNoNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_MobileTelNoNumber"), @"");
			}
			set
			{
				SetValue("ContactDetails_MobileTelNoNumber", value);
			}
		}


		/// <summary>
		/// Home Tel. No. (Incl. country code).
		/// </summary>
		[DatabaseField]
		public string ContactDetails_HomeTelNoNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_HomeTelNoNumber"), @"");
			}
			set
			{
				SetValue("ContactDetails_HomeTelNoNumber", value);
			}
		}


		/// <summary>
		/// Work Tel. No. (Incl. country code).
		/// </summary>
		[DatabaseField]
		public string ContactDetails_WorkTelNoNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_WorkTelNoNumber"), @"");
			}
			set
			{
				SetValue("ContactDetails_WorkTelNoNumber", value);
			}
		}


		/// <summary>
		/// Fax No. (Incl. country code).
		/// </summary>
		[DatabaseField]
		public string ContactDetails_FaxNoFaxNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_FaxNoFaxNumber"), @"");
			}
			set
			{
				SetValue("ContactDetails_FaxNoFaxNumber", value);
			}
		}


		/// <summary>
		/// Email Address.
		/// </summary>
		[DatabaseField]
		public string ContactDetails_EmailAddress
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactDetails_EmailAddress"), @"");
			}
			set
			{
				SetValue("ContactDetails_EmailAddress", value);
			}
		}


		/// <summary>
		/// Preferred Communication Language.
		/// </summary>
		[DatabaseField]
		public Guid ContactDetails_PreferredCommunicationLanguage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("ContactDetails_PreferredCommunicationLanguage"), Guid.Empty);
			}
			set
			{
				SetValue("ContactDetails_PreferredCommunicationLanguage", value);
			}
		}


		/// <summary>
		/// Consent for Marketing Purposes.
		/// </summary>
		[DatabaseField]
		public bool ContactDetails_ConsentForMarketingPurposes
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("ContactDetails_ConsentForMarketingPurposes"), true);
			}
			set
			{
				SetValue("ContactDetails_ConsentForMarketingPurposes", value);
			}
		}


		/// <summary>
		/// Save In Registry.
		/// </summary>
		[DatabaseField]
		public bool ContactDetails_SaveInRegistry
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("ContactDetails_SaveInRegistry"), true);
			}
			set
			{
				SetValue("ContactDetails_SaveInRegistry", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactDetails fields.
		/// </summary>
		[RegisterProperty]
		public ContactDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactDetailsFields : AbstractHierarchicalObject<ContactDetailsFields>
		{
			/// <summary>
			/// The content item of type ContactDetails that is a target of the extended API.
			/// </summary>
			private readonly ContactDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactDetailsFields" /> class with the specified content item of type ContactDetails.
			/// </summary>
			/// <param name="instance">The content item of type ContactDetails that is a target of the extended API.</param>
			public ContactDetailsFields(ContactDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactDetailsID;
				}
				set
				{
					mInstance.ContactDetailsID = value;
				}
			}


			/// <summary>
			/// Mobile Country Code.
			/// </summary>
			public string _Mobile_CountryCode
			{
				get
				{
					return mInstance.ContactDetails_Mobile_CountryCode;
				}
				set
				{
					mInstance.ContactDetails_Mobile_CountryCode = value;
				}
			}


			/// <summary>
			/// Home Country Code.
			/// </summary>
			public string _Home_CountryCode
			{
				get
				{
					return mInstance.ContactDetails_Home_CountryCode;
				}
				set
				{
					mInstance.ContactDetails_Home_CountryCode = value;
				}
			}


			/// <summary>
			/// Work Country Code.
			/// </summary>
			public string _Work_CountryCode
			{
				get
				{
					return mInstance.ContactDetails_Work_CountryCode;
				}
				set
				{
					mInstance.ContactDetails_Work_CountryCode = value;
				}
			}


			/// <summary>
			/// Fax Country Code.
			/// </summary>
			public string _Fax_CountryCode
			{
				get
				{
					return mInstance.ContactDetails_Fax_CountryCode;
				}
				set
				{
					mInstance.ContactDetails_Fax_CountryCode = value;
				}
			}


			/// <summary>
			/// Mobile Tel. No. (Incl. country code).
			/// </summary>
			public string _MobileTelNoNumber
			{
				get
				{
					return mInstance.ContactDetails_MobileTelNoNumber;
				}
				set
				{
					mInstance.ContactDetails_MobileTelNoNumber = value;
				}
			}


			/// <summary>
			/// Home Tel. No. (Incl. country code).
			/// </summary>
			public string _HomeTelNoNumber
			{
				get
				{
					return mInstance.ContactDetails_HomeTelNoNumber;
				}
				set
				{
					mInstance.ContactDetails_HomeTelNoNumber = value;
				}
			}


			/// <summary>
			/// Work Tel. No. (Incl. country code).
			/// </summary>
			public string _WorkTelNoNumber
			{
				get
				{
					return mInstance.ContactDetails_WorkTelNoNumber;
				}
				set
				{
					mInstance.ContactDetails_WorkTelNoNumber = value;
				}
			}


			/// <summary>
			/// Fax No. (Incl. country code).
			/// </summary>
			public string _FaxNoFaxNumber
			{
				get
				{
					return mInstance.ContactDetails_FaxNoFaxNumber;
				}
				set
				{
					mInstance.ContactDetails_FaxNoFaxNumber = value;
				}
			}


			/// <summary>
			/// Email Address.
			/// </summary>
			public string _EmailAddress
			{
				get
				{
					return mInstance.ContactDetails_EmailAddress;
				}
				set
				{
					mInstance.ContactDetails_EmailAddress = value;
				}
			}


			/// <summary>
			/// Preferred Communication Language.
			/// </summary>
			public Guid _PreferredCommunicationLanguage
			{
				get
				{
					return mInstance.ContactDetails_PreferredCommunicationLanguage;
				}
				set
				{
					mInstance.ContactDetails_PreferredCommunicationLanguage = value;
				}
			}


			/// <summary>
			/// Consent for Marketing Purposes.
			/// </summary>
			public bool _ConsentForMarketingPurposes
			{
				get
				{
					return mInstance.ContactDetails_ConsentForMarketingPurposes;
				}
				set
				{
					mInstance.ContactDetails_ConsentForMarketingPurposes = value;
				}
			}


			/// <summary>
			/// Save In Registry.
			/// </summary>
			public bool _SaveInRegistry
			{
				get
				{
					return mInstance.ContactDetails_SaveInRegistry;
				}
				set
				{
					mInstance.ContactDetails_SaveInRegistry = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactDetails" /> class.
		/// </summary>
		public ContactDetails() : base(CLASS_NAME)
		{
			mFields = new ContactDetailsFields(this);
		}

		#endregion
	}
}