//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(LookupItem.CLASS_NAME, typeof(LookupItem))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type LookupItem.
	/// </summary>
	public partial class LookupItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.LookupItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with LookupItem fields.
		/// </summary>
		private readonly LookupItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// LookupItemID.
		/// </summary>
		[DatabaseIDField]
		public int LookupItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LookupItemID"), 0);
			}
			set
			{
				SetValue("LookupItemID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string LookupItemName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LookupItemName"), @"");
			}
			set
			{
				SetValue("LookupItemName", value);
			}
		}


		/// <summary>
		/// Code.
		/// </summary>
		[DatabaseField]
		public string LookupItemCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LookupItemCode"), @"");
			}
			set
			{
				SetValue("LookupItemCode", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with LookupItem fields.
		/// </summary>
		[RegisterProperty]
		public LookupItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with LookupItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class LookupItemFields : AbstractHierarchicalObject<LookupItemFields>
		{
			/// <summary>
			/// The content item of type LookupItem that is a target of the extended API.
			/// </summary>
			private readonly LookupItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="LookupItemFields" /> class with the specified content item of type LookupItem.
			/// </summary>
			/// <param name="instance">The content item of type LookupItem that is a target of the extended API.</param>
			public LookupItemFields(LookupItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// LookupItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.LookupItemID;
				}
				set
				{
					mInstance.LookupItemID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.LookupItemName;
				}
				set
				{
					mInstance.LookupItemName = value;
				}
			}


			/// <summary>
			/// Code.
			/// </summary>
			public string Code
			{
				get
				{
					return mInstance.LookupItemCode;
				}
				set
				{
					mInstance.LookupItemCode = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="LookupItem" /> class.
		/// </summary>
		public LookupItem() : base(CLASS_NAME)
		{
			mFields = new LookupItemFields(this);
		}

		#endregion
	}
}