//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(AddressDetails.CLASS_NAME, typeof(AddressDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type AddressDetails.
	/// </summary>
	public partial class AddressDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.AddressDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with AddressDetails fields.
		/// </summary>
		private readonly AddressDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AddressDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int AddressDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AddressDetailsID"), 0);
			}
			set
			{
				SetValue("AddressDetailsID", value);
			}
		}


		/// <summary>
		/// Number of staff employed.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_NumberOfStaffEmployed
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_NumberOfStaffEmployed"), @"");
			}
			set
			{
				SetValue("AddressDetails_NumberOfStaffEmployed", value);
			}
		}


		/// <summary>
		/// Country Code PhoneNo.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_CountryCode_PhoneNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_CountryCode_PhoneNo"), @"");
			}
			set
			{
				SetValue("AddressDetails_CountryCode_PhoneNo", value);
			}
		}


		/// <summary>
		/// Country Code FaxNo.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_CountryCode_FaxNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_CountryCode_FaxNo"), @"");
			}
			set
			{
				SetValue("AddressDetails_CountryCode_FaxNo", value);
			}
		}


		/// <summary>
		/// Address Details Is Legal.
		/// </summary>
		[DatabaseField]
		public bool AddressDetails_Is_Legal
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AddressDetails_Is_Legal"), false);
			}
			set
			{
				SetValue("AddressDetails_Is_Legal", value);
			}
		}


		/// <summary>
		/// Address Details Phone No.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_Phone_No
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_Phone_No"), @"");
			}
			set
			{
				SetValue("AddressDetails_Phone_No", value);
			}
		}


		/// <summary>
		/// Address Details Fax No.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_Fax_No
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_Fax_No"), @"");
			}
			set
			{
				SetValue("AddressDetails_Fax_No", value);
			}
		}


		/// <summary>
		/// Status.
		/// </summary>
		[DatabaseField]
		public bool AddressDetails_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AddressDetails_Status"), false);
			}
			set
			{
				SetValue("AddressDetails_Status", value);
			}
		}


		/// <summary>
		/// Address Type.
		/// </summary>
		[DatabaseField]
		public Guid AddressDetails_AddressType
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("AddressDetails_AddressType"), Guid.Empty);
			}
			set
			{
				SetValue("AddressDetails_AddressType", value);
			}
		}


		/// <summary>
		/// Please enter Street Name and Details:  No, Flat No.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_AddressLine1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_AddressLine1"), @"");
			}
			set
			{
				SetValue("AddressDetails_AddressLine1", value);
			}
		}


		/// <summary>
		/// Address Line 2 .
		/// </summary>
		[DatabaseField]
		public string AddressDetails_AddressLine2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_AddressLine2"), @"");
			}
			set
			{
				SetValue("AddressDetails_AddressLine2", value);
			}
		}


		/// <summary>
		/// Postal Code.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_PostalCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_PostalCode"), @"");
			}
			set
			{
				SetValue("AddressDetails_PostalCode", value);
			}
		}


		/// <summary>
		/// Address Details PO Box.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_POBox
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_POBox"), @"");
			}
			set
			{
				SetValue("AddressDetails_POBox", value);
			}
		}


		/// <summary>
		/// Town / City / Village.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_City
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_City"), @"");
			}
			set
			{
				SetValue("AddressDetails_City", value);
			}
		}


		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_Country
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_Country"), @"");
			}
			set
			{
				SetValue("AddressDetails_Country", value);
			}
		}


		/// <summary>
		/// Save In Registry.
		/// </summary>
		[DatabaseField]
		public bool AddressDetails_SaveInRegistry
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AddressDetails_SaveInRegistry"), true);
			}
			set
			{
				SetValue("AddressDetails_SaveInRegistry", value);
			}
		}


		/// <summary>
		/// Main Correspondence Address.
		/// </summary>
		[DatabaseField]
		public bool AddressDetails_MainCorrespondenceAddress
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("AddressDetails_MainCorrespondenceAddress"), false);
			}
			set
			{
				SetValue("AddressDetails_MainCorrespondenceAddress", value);
			}
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_Email
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_Email"), @"");
			}
			set
			{
				SetValue("AddressDetails_Email", value);
			}
		}


		/// <summary>
		/// Location Name.
		/// </summary>
		[DatabaseField]
		public string AddressDetails_LocationName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressDetails_LocationName"), @"");
			}
			set
			{
				SetValue("AddressDetails_LocationName", value);
			}
		}


		/// <summary>
		/// AddressDetails_RegistryId.
		/// </summary>
		[DatabaseField]
		public int AddressDetails_RegistryId
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AddressDetails_RegistryId"), 0);
			}
			set
			{
				SetValue("AddressDetails_RegistryId", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AddressDetails fields.
		/// </summary>
		[RegisterProperty]
		public AddressDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AddressDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AddressDetailsFields : AbstractHierarchicalObject<AddressDetailsFields>
		{
			/// <summary>
			/// The content item of type AddressDetails that is a target of the extended API.
			/// </summary>
			private readonly AddressDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AddressDetailsFields" /> class with the specified content item of type AddressDetails.
			/// </summary>
			/// <param name="instance">The content item of type AddressDetails that is a target of the extended API.</param>
			public AddressDetailsFields(AddressDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AddressDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AddressDetailsID;
				}
				set
				{
					mInstance.AddressDetailsID = value;
				}
			}


			/// <summary>
			/// Number of staff employed.
			/// </summary>
			public string _NumberOfStaffEmployed
			{
				get
				{
					return mInstance.AddressDetails_NumberOfStaffEmployed;
				}
				set
				{
					mInstance.AddressDetails_NumberOfStaffEmployed = value;
				}
			}


			/// <summary>
			/// Country Code PhoneNo.
			/// </summary>
			public string _CountryCode_PhoneNo
			{
				get
				{
					return mInstance.AddressDetails_CountryCode_PhoneNo;
				}
				set
				{
					mInstance.AddressDetails_CountryCode_PhoneNo = value;
				}
			}


			/// <summary>
			/// Country Code FaxNo.
			/// </summary>
			public string _CountryCode_FaxNo
			{
				get
				{
					return mInstance.AddressDetails_CountryCode_FaxNo;
				}
				set
				{
					mInstance.AddressDetails_CountryCode_FaxNo = value;
				}
			}


			/// <summary>
			/// Address Details Is Legal.
			/// </summary>
			public bool _Is_Legal
			{
				get
				{
					return mInstance.AddressDetails_Is_Legal;
				}
				set
				{
					mInstance.AddressDetails_Is_Legal = value;
				}
			}


			/// <summary>
			/// Address Details Phone No.
			/// </summary>
			public string _Phone_No
			{
				get
				{
					return mInstance.AddressDetails_Phone_No;
				}
				set
				{
					mInstance.AddressDetails_Phone_No = value;
				}
			}


			/// <summary>
			/// Address Details Fax No.
			/// </summary>
			public string _Fax_No
			{
				get
				{
					return mInstance.AddressDetails_Fax_No;
				}
				set
				{
					mInstance.AddressDetails_Fax_No = value;
				}
			}


			/// <summary>
			/// Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.AddressDetails_Status;
				}
				set
				{
					mInstance.AddressDetails_Status = value;
				}
			}


			/// <summary>
			/// Address Type.
			/// </summary>
			public Guid _AddressType
			{
				get
				{
					return mInstance.AddressDetails_AddressType;
				}
				set
				{
					mInstance.AddressDetails_AddressType = value;
				}
			}


			/// <summary>
			/// Please enter Street Name and Details:  No, Flat No.
			/// </summary>
			public string _AddressLine1
			{
				get
				{
					return mInstance.AddressDetails_AddressLine1;
				}
				set
				{
					mInstance.AddressDetails_AddressLine1 = value;
				}
			}


			/// <summary>
			/// Address Line 2 .
			/// </summary>
			public string _AddressLine2
			{
				get
				{
					return mInstance.AddressDetails_AddressLine2;
				}
				set
				{
					mInstance.AddressDetails_AddressLine2 = value;
				}
			}


			/// <summary>
			/// Postal Code.
			/// </summary>
			public string _PostalCode
			{
				get
				{
					return mInstance.AddressDetails_PostalCode;
				}
				set
				{
					mInstance.AddressDetails_PostalCode = value;
				}
			}


			/// <summary>
			/// Address Details PO Box.
			/// </summary>
			public string _POBox
			{
				get
				{
					return mInstance.AddressDetails_POBox;
				}
				set
				{
					mInstance.AddressDetails_POBox = value;
				}
			}


			/// <summary>
			/// Town / City / Village.
			/// </summary>
			public string _City
			{
				get
				{
					return mInstance.AddressDetails_City;
				}
				set
				{
					mInstance.AddressDetails_City = value;
				}
			}


			/// <summary>
			/// Country.
			/// </summary>
			public string _Country
			{
				get
				{
					return mInstance.AddressDetails_Country;
				}
				set
				{
					mInstance.AddressDetails_Country = value;
				}
			}


			/// <summary>
			/// Save In Registry.
			/// </summary>
			public bool _SaveInRegistry
			{
				get
				{
					return mInstance.AddressDetails_SaveInRegistry;
				}
				set
				{
					mInstance.AddressDetails_SaveInRegistry = value;
				}
			}


			/// <summary>
			/// Main Correspondence Address.
			/// </summary>
			public bool _MainCorrespondenceAddress
			{
				get
				{
					return mInstance.AddressDetails_MainCorrespondenceAddress;
				}
				set
				{
					mInstance.AddressDetails_MainCorrespondenceAddress = value;
				}
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string _Email
			{
				get
				{
					return mInstance.AddressDetails_Email;
				}
				set
				{
					mInstance.AddressDetails_Email = value;
				}
			}


			/// <summary>
			/// Location Name.
			/// </summary>
			public string _LocationName
			{
				get
				{
					return mInstance.AddressDetails_LocationName;
				}
				set
				{
					mInstance.AddressDetails_LocationName = value;
				}
			}


			/// <summary>
			/// AddressDetails_RegistryId.
			/// </summary>
			public int _RegistryId
			{
				get
				{
					return mInstance.AddressDetails_RegistryId;
				}
				set
				{
					mInstance.AddressDetails_RegistryId = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AddressDetails" /> class.
		/// </summary>
		public AddressDetails() : base(CLASS_NAME)
		{
			mFields = new AddressDetailsFields(this);
		}

		#endregion
	}
}