//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(BankUnit.CLASS_NAME, typeof(BankUnit))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type BankUnit.
	/// </summary>
	public partial class BankUnit : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.BankUnit";


		/// <summary>
		/// The instance of the class that provides extended API for working with BankUnit fields.
		/// </summary>
		private readonly BankUnitFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BankUnitID.
		/// </summary>
		[DatabaseIDField]
		public int BankUnitID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BankUnitID"), 0);
			}
			set
			{
				SetValue("BankUnitID", value);
			}
		}


		/// <summary>
		/// Unit Name.
		/// </summary>
		[DatabaseField]
		public string BankUnitName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitName"), @"");
			}
			set
			{
				SetValue("BankUnitName", value);
			}
		}


		/// <summary>
		/// Unit Code.
		/// </summary>
		[DatabaseField]
		public string BankUnitCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitCode"), @"");
			}
			set
			{
				SetValue("BankUnitCode", value);
			}
		}


		/// <summary>
		/// Parent Unit Number.
		/// </summary>
		[DatabaseField]
		public string BankUnitParentUnitNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitParentUnitNumber"), @"");
			}
			set
			{
				SetValue("BankUnitParentUnitNumber", value);
			}
		}


		/// <summary>
		/// Can Receive Applications.
		/// </summary>
		[DatabaseField]
		public bool BankUnitCanReceiveApplications
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("BankUnitCanReceiveApplications"), false);
			}
			set
			{
				SetValue("BankUnitCanReceiveApplications", value);
			}
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string BankUnitEmail
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitEmail"), @"");
			}
			set
			{
				SetValue("BankUnitEmail", value);
			}
		}


		/// <summary>
		/// Address.
		/// </summary>
		[DatabaseField]
		public string BankUnitAddress
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitAddress"), @"");
			}
			set
			{
				SetValue("BankUnitAddress", value);
			}
		}


		/// <summary>
		/// PO Box.
		/// </summary>
		[DatabaseField]
		public string BankUnitPOBox
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitPOBox"), @"");
			}
			set
			{
				SetValue("BankUnitPOBox", value);
			}
		}


		/// <summary>
		/// Telephone.
		/// </summary>
		[DatabaseField]
		public string BankUnitTelephone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitTelephone"), @"");
			}
			set
			{
				SetValue("BankUnitTelephone", value);
			}
		}


		/// <summary>
		/// Fax.
		/// </summary>
		[DatabaseField]
		public string BankUnitFax
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BankUnitFax"), @"");
			}
			set
			{
				SetValue("BankUnitFax", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BankUnit fields.
		/// </summary>
		[RegisterProperty]
		public BankUnitFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BankUnit fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BankUnitFields : AbstractHierarchicalObject<BankUnitFields>
		{
			/// <summary>
			/// The content item of type BankUnit that is a target of the extended API.
			/// </summary>
			private readonly BankUnit mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BankUnitFields" /> class with the specified content item of type BankUnit.
			/// </summary>
			/// <param name="instance">The content item of type BankUnit that is a target of the extended API.</param>
			public BankUnitFields(BankUnit instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BankUnitID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BankUnitID;
				}
				set
				{
					mInstance.BankUnitID = value;
				}
			}


			/// <summary>
			/// Unit Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.BankUnitName;
				}
				set
				{
					mInstance.BankUnitName = value;
				}
			}


			/// <summary>
			/// Unit Code.
			/// </summary>
			public string Code
			{
				get
				{
					return mInstance.BankUnitCode;
				}
				set
				{
					mInstance.BankUnitCode = value;
				}
			}


			/// <summary>
			/// Parent Unit Number.
			/// </summary>
			public string ParentUnitNumber
			{
				get
				{
					return mInstance.BankUnitParentUnitNumber;
				}
				set
				{
					mInstance.BankUnitParentUnitNumber = value;
				}
			}


			/// <summary>
			/// Can Receive Applications.
			/// </summary>
			public bool CanReceiveApplications
			{
				get
				{
					return mInstance.BankUnitCanReceiveApplications;
				}
				set
				{
					mInstance.BankUnitCanReceiveApplications = value;
				}
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get
				{
					return mInstance.BankUnitEmail;
				}
				set
				{
					mInstance.BankUnitEmail = value;
				}
			}


			/// <summary>
			/// Address.
			/// </summary>
			public string Address
			{
				get
				{
					return mInstance.BankUnitAddress;
				}
				set
				{
					mInstance.BankUnitAddress = value;
				}
			}


			/// <summary>
			/// PO Box.
			/// </summary>
			public string POBox
			{
				get
				{
					return mInstance.BankUnitPOBox;
				}
				set
				{
					mInstance.BankUnitPOBox = value;
				}
			}


			/// <summary>
			/// Telephone.
			/// </summary>
			public string Telephone
			{
				get
				{
					return mInstance.BankUnitTelephone;
				}
				set
				{
					mInstance.BankUnitTelephone = value;
				}
			}


			/// <summary>
			/// Fax.
			/// </summary>
			public string Fax
			{
				get
				{
					return mInstance.BankUnitFax;
				}
				set
				{
					mInstance.BankUnitFax = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BankUnit" /> class.
		/// </summary>
		public BankUnit() : base(CLASS_NAME)
		{
			mFields = new BankUnitFields(this);
		}

		#endregion
	}
}