//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(PersonalDetails.CLASS_NAME, typeof(PersonalDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type PersonalDetails.
	/// </summary>
	public partial class PersonalDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.PersonalDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with PersonalDetails fields.
		/// </summary>
		private readonly PersonalDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PersonalDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int PersonalDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonalDetailsID"), 0);
			}
			set
			{
				SetValue("PersonalDetailsID", value);
			}
		}


		/// <summary>
		/// PersonalDetails_HIDInviteFlag.
		/// </summary>
		[DatabaseField]
		public int PersonalDetails_HIDInviteFlag
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonalDetails_HIDInviteFlag"), 0);
			}
			set
			{
				SetValue("PersonalDetails_HIDInviteFlag", value);
			}
		}


		/// <summary>
		/// Is Related Party a UBO?.
		/// </summary>
		[DatabaseField]
		public bool PersonalDetails_IsRelatedPartyUBO
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("PersonalDetails_IsRelatedPartyUBO"), false);
			}
			set
			{
				SetValue("PersonalDetails_IsRelatedPartyUBO", value);
			}
		}


		/// <summary>
		/// CustomerCIF.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_CustomerCIF
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_CustomerCIF"), @"");
			}
			set
			{
				SetValue("PersonalDetails_CustomerCIF", value);
			}
		}


		/// <summary>
		/// Invited.
		/// </summary>
		[DatabaseField]
		public int PersonalDetails_Invited
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonalDetails_Invited"), 0);
			}
			set
			{
				SetValue("PersonalDetails_Invited", value);
			}
		}


		/// <summary>
		/// PersonalDetails_Status.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_Status
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_Status"), @"");
			}
			set
			{
				SetValue("PersonalDetails_Status", value);
			}
		}


		/// <summary>
		/// PersonRegistryId.
		/// </summary>
		[DatabaseField]
		public int PersonRegistryId
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonRegistryId"), 0);
			}
			set
			{
				SetValue("PersonRegistryId", value);
			}
		}


		/// <summary>
		/// ID Verified.
		/// </summary>
		[DatabaseField]
		public bool PersonalDetails_IdVerified
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("PersonalDetails_IdVerified"), false);
			}
			set
			{
				SetValue("PersonalDetails_IdVerified", value);
			}
		}


		/// <summary>
		/// Personal Details Application Type.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_Type
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_Type"), @"");
			}
			set
			{
				SetValue("PersonalDetails_Type", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public Guid PersonalDetails_Title
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("PersonalDetails_Title"), Guid.Empty);
			}
			set
			{
				SetValue("PersonalDetails_Title", value);
			}
		}


		/// <summary>
		/// First Name.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_FirstName"), @"");
			}
			set
			{
				SetValue("PersonalDetails_FirstName", value);
			}
		}


		/// <summary>
		/// Last Name.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_LastName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_LastName"), @"");
			}
			set
			{
				SetValue("PersonalDetails_LastName", value);
			}
		}


		/// <summary>
		/// Father's Name.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_FathersName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_FathersName"), @"");
			}
			set
			{
				SetValue("PersonalDetails_FathersName", value);
			}
		}


		/// <summary>
		/// Gender.
		/// </summary>
		[DatabaseField]
		public Guid PersonalDetails_Gender
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("PersonalDetails_Gender"), Guid.Empty);
			}
			set
			{
				SetValue("PersonalDetails_Gender", value);
			}
		}


		/// <summary>
		/// Date of Birth.
		/// </summary>
		[DatabaseField]
		public DateTime PersonalDetails_DateOfBirth
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("PersonalDetails_DateOfBirth"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("PersonalDetails_DateOfBirth", value);
			}
		}


		/// <summary>
		/// Place of Birth.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_PlaceOfBirth
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_PlaceOfBirth"), @"");
			}
			set
			{
				SetValue("PersonalDetails_PlaceOfBirth", value);
			}
		}


		/// <summary>
		/// Country of Birth.
		/// </summary>
		[DatabaseField]
		public int PersonalDetails_CountryOfBirth
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonalDetails_CountryOfBirth"), 0);
			}
			set
			{
				SetValue("PersonalDetails_CountryOfBirth", value);
			}
		}


		/// <summary>
		/// Education Level.
		/// </summary>
		[DatabaseField]
		public Guid PersonalDetails_EducationLevel
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("PersonalDetails_EducationLevel"), Guid.Empty);
			}
			set
			{
				SetValue("PersonalDetails_EducationLevel", value);
			}
		}


		/// <summary>
		/// Is the applicant liable to pay defense tax in Cyprus? .
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_IsLiableToPayDefenseTaxInCyprus
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_IsLiableToPayDefenseTaxInCyprus"), @"");
			}
			set
			{
				SetValue("PersonalDetails_IsLiableToPayDefenseTaxInCyprus", value);
			}
		}


		/// <summary>
		/// Is he/she a PEP?.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_IsPep
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_IsPep"), @"");
			}
			set
			{
				SetValue("PersonalDetails_IsPep", value);
			}
		}


		/// <summary>
		/// Is he/she an immediate family member or close associate a PEP?.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_IsRelatedToPep
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_IsRelatedToPep"), @"");
			}
			set
			{
				SetValue("PersonalDetails_IsRelatedToPep", value);
			}
		}


		/// <summary>
		/// Does the Applicant maintain Bank Account(s) with another Banking Institution?.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_HasAccountInOtherBank
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_HasAccountInOtherBank"), @"");
			}
			set
			{
				SetValue("PersonalDetails_HasAccountInOtherBank", value);
			}
		}


		/// <summary>
		/// Name of Banking Institution.
		/// </summary>
		[DatabaseField]
		public string PersonalDetails_NameOfBankingInstitution
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetails_NameOfBankingInstitution"), @"");
			}
			set
			{
				SetValue("PersonalDetails_NameOfBankingInstitution", value);
			}
		}


		/// <summary>
		/// Country of Banking Institution.
		/// </summary>
		[DatabaseField]
		public int PersonalDetails_CountryOfBankingInstitution
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonalDetails_CountryOfBankingInstitution"), 0);
			}
			set
			{
				SetValue("PersonalDetails_CountryOfBankingInstitution", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PersonalDetails fields.
		/// </summary>
		[RegisterProperty]
		public PersonalDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PersonalDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PersonalDetailsFields : AbstractHierarchicalObject<PersonalDetailsFields>
		{
			/// <summary>
			/// The content item of type PersonalDetails that is a target of the extended API.
			/// </summary>
			private readonly PersonalDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PersonalDetailsFields" /> class with the specified content item of type PersonalDetails.
			/// </summary>
			/// <param name="instance">The content item of type PersonalDetails that is a target of the extended API.</param>
			public PersonalDetailsFields(PersonalDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PersonalDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PersonalDetailsID;
				}
				set
				{
					mInstance.PersonalDetailsID = value;
				}
			}


			/// <summary>
			/// PersonalDetails_HIDInviteFlag.
			/// </summary>
			public int _HIDInviteFlag
			{
				get
				{
					return mInstance.PersonalDetails_HIDInviteFlag;
				}
				set
				{
					mInstance.PersonalDetails_HIDInviteFlag = value;
				}
			}


			/// <summary>
			/// Is Related Party a UBO?.
			/// </summary>
			public bool _IsRelatedPartyUBO
			{
				get
				{
					return mInstance.PersonalDetails_IsRelatedPartyUBO;
				}
				set
				{
					mInstance.PersonalDetails_IsRelatedPartyUBO = value;
				}
			}


			/// <summary>
			/// CustomerCIF.
			/// </summary>
			public string _CustomerCIF
			{
				get
				{
					return mInstance.PersonalDetails_CustomerCIF;
				}
				set
				{
					mInstance.PersonalDetails_CustomerCIF = value;
				}
			}


			/// <summary>
			/// Invited.
			/// </summary>
			public int _Invited
			{
				get
				{
					return mInstance.PersonalDetails_Invited;
				}
				set
				{
					mInstance.PersonalDetails_Invited = value;
				}
			}


			/// <summary>
			/// PersonalDetails_Status.
			/// </summary>
			public string _Status
			{
				get
				{
					return mInstance.PersonalDetails_Status;
				}
				set
				{
					mInstance.PersonalDetails_Status = value;
				}
			}


			/// <summary>
			/// PersonRegistryId.
			/// </summary>
			public int PersonRegistryId
			{
				get
				{
					return mInstance.PersonRegistryId;
				}
				set
				{
					mInstance.PersonRegistryId = value;
				}
			}


			/// <summary>
			/// ID Verified.
			/// </summary>
			public bool _IdVerified
			{
				get
				{
					return mInstance.PersonalDetails_IdVerified;
				}
				set
				{
					mInstance.PersonalDetails_IdVerified = value;
				}
			}


			/// <summary>
			/// Personal Details Application Type.
			/// </summary>
			public string _Type
			{
				get
				{
					return mInstance.PersonalDetails_Type;
				}
				set
				{
					mInstance.PersonalDetails_Type = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public Guid _Title
			{
				get
				{
					return mInstance.PersonalDetails_Title;
				}
				set
				{
					mInstance.PersonalDetails_Title = value;
				}
			}


			/// <summary>
			/// First Name.
			/// </summary>
			public string _FirstName
			{
				get
				{
					return mInstance.PersonalDetails_FirstName;
				}
				set
				{
					mInstance.PersonalDetails_FirstName = value;
				}
			}


			/// <summary>
			/// Last Name.
			/// </summary>
			public string _LastName
			{
				get
				{
					return mInstance.PersonalDetails_LastName;
				}
				set
				{
					mInstance.PersonalDetails_LastName = value;
				}
			}


			/// <summary>
			/// Father's Name.
			/// </summary>
			public string _FathersName
			{
				get
				{
					return mInstance.PersonalDetails_FathersName;
				}
				set
				{
					mInstance.PersonalDetails_FathersName = value;
				}
			}


			/// <summary>
			/// Gender.
			/// </summary>
			public Guid _Gender
			{
				get
				{
					return mInstance.PersonalDetails_Gender;
				}
				set
				{
					mInstance.PersonalDetails_Gender = value;
				}
			}


			/// <summary>
			/// Date of Birth.
			/// </summary>
			public DateTime _DateOfBirth
			{
				get
				{
					return mInstance.PersonalDetails_DateOfBirth;
				}
				set
				{
					mInstance.PersonalDetails_DateOfBirth = value;
				}
			}


			/// <summary>
			/// Place of Birth.
			/// </summary>
			public string _PlaceOfBirth
			{
				get
				{
					return mInstance.PersonalDetails_PlaceOfBirth;
				}
				set
				{
					mInstance.PersonalDetails_PlaceOfBirth = value;
				}
			}


			/// <summary>
			/// Country of Birth.
			/// </summary>
			public int _CountryOfBirth
			{
				get
				{
					return mInstance.PersonalDetails_CountryOfBirth;
				}
				set
				{
					mInstance.PersonalDetails_CountryOfBirth = value;
				}
			}


			/// <summary>
			/// Education Level.
			/// </summary>
			public Guid _EducationLevel
			{
				get
				{
					return mInstance.PersonalDetails_EducationLevel;
				}
				set
				{
					mInstance.PersonalDetails_EducationLevel = value;
				}
			}


			/// <summary>
			/// Is the applicant liable to pay defense tax in Cyprus? .
			/// </summary>
			public string _IsLiableToPayDefenseTaxInCyprus
			{
				get
				{
					return mInstance.PersonalDetails_IsLiableToPayDefenseTaxInCyprus;
				}
				set
				{
					mInstance.PersonalDetails_IsLiableToPayDefenseTaxInCyprus = value;
				}
			}


			/// <summary>
			/// Is he/she a PEP?.
			/// </summary>
			public string _IsPep
			{
				get
				{
					return mInstance.PersonalDetails_IsPep;
				}
				set
				{
					mInstance.PersonalDetails_IsPep = value;
				}
			}


			/// <summary>
			/// Is he/she an immediate family member or close associate a PEP?.
			/// </summary>
			public string _IsRelatedToPep
			{
				get
				{
					return mInstance.PersonalDetails_IsRelatedToPep;
				}
				set
				{
					mInstance.PersonalDetails_IsRelatedToPep = value;
				}
			}


			/// <summary>
			/// Does the Applicant maintain Bank Account(s) with another Banking Institution?.
			/// </summary>
			public string _HasAccountInOtherBank
			{
				get
				{
					return mInstance.PersonalDetails_HasAccountInOtherBank;
				}
				set
				{
					mInstance.PersonalDetails_HasAccountInOtherBank = value;
				}
			}


			/// <summary>
			/// Name of Banking Institution.
			/// </summary>
			public string _NameOfBankingInstitution
			{
				get
				{
					return mInstance.PersonalDetails_NameOfBankingInstitution;
				}
				set
				{
					mInstance.PersonalDetails_NameOfBankingInstitution = value;
				}
			}


			/// <summary>
			/// Country of Banking Institution.
			/// </summary>
			public int _CountryOfBankingInstitution
			{
				get
				{
					return mInstance.PersonalDetails_CountryOfBankingInstitution;
				}
				set
				{
					mInstance.PersonalDetails_CountryOfBankingInstitution = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PersonalDetails" /> class.
		/// </summary>
		public PersonalDetails() : base(CLASS_NAME)
		{
			mFields = new PersonalDetailsFields(this);
		}

		#endregion
	}
}