//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(Accounts.CLASS_NAME, typeof(Accounts))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type Accounts.
	/// </summary>
	public partial class Accounts : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.Accounts";


		/// <summary>
		/// The instance of the class that provides extended API for working with Accounts fields.
		/// </summary>
		private readonly AccountsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AccountsID.
		/// </summary>
		[DatabaseIDField]
		public int AccountsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AccountsID"), 0);
			}
			set
			{
				SetValue("AccountsID", value);
			}
		}


		/// <summary>
		/// Account Type.
		/// </summary>
		[DatabaseField]
		public Guid Accounts_AccountType
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Accounts_AccountType"), Guid.Empty);
			}
			set
			{
				SetValue("Accounts_AccountType", value);
			}
		}


		/// <summary>
		/// Account Status.
		/// </summary>
		[DatabaseField]
		public bool Accounts_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Accounts_Status"), false);
			}
			set
			{
				SetValue("Accounts_Status", value);
			}
		}


		/// <summary>
		/// Currency.
		/// </summary>
		[DatabaseField]
		public Guid Accounts_Currency
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Accounts_Currency"), Guid.Empty);
			}
			set
			{
				SetValue("Accounts_Currency", value);
			}
		}


		/// <summary>
		///  Statement Frequency.
		/// </summary>
		[DatabaseField]
		public Guid Accounts_StatementFrequency
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Accounts_StatementFrequency"), Guid.Empty);
			}
			set
			{
				SetValue("Accounts_StatementFrequency", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Accounts fields.
		/// </summary>
		[RegisterProperty]
		public AccountsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Accounts fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AccountsFields : AbstractHierarchicalObject<AccountsFields>
		{
			/// <summary>
			/// The content item of type Accounts that is a target of the extended API.
			/// </summary>
			private readonly Accounts mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AccountsFields" /> class with the specified content item of type Accounts.
			/// </summary>
			/// <param name="instance">The content item of type Accounts that is a target of the extended API.</param>
			public AccountsFields(Accounts instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AccountsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AccountsID;
				}
				set
				{
					mInstance.AccountsID = value;
				}
			}


			/// <summary>
			/// Account Type.
			/// </summary>
			public Guid _AccountType
			{
				get
				{
					return mInstance.Accounts_AccountType;
				}
				set
				{
					mInstance.Accounts_AccountType = value;
				}
			}


			/// <summary>
			/// Account Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.Accounts_Status;
				}
				set
				{
					mInstance.Accounts_Status = value;
				}
			}


			/// <summary>
			/// Currency.
			/// </summary>
			public Guid _Currency
			{
				get
				{
					return mInstance.Accounts_Currency;
				}
				set
				{
					mInstance.Accounts_Currency = value;
				}
			}


			/// <summary>
			///  Statement Frequency.
			/// </summary>
			public Guid _StatementFrequency
			{
				get
				{
					return mInstance.Accounts_StatementFrequency;
				}
				set
				{
					mInstance.Accounts_StatementFrequency = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Accounts" /> class.
		/// </summary>
		public Accounts() : base(CLASS_NAME)
		{
			mFields = new AccountsFields(this);
		}

		#endregion
	}
}