//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(PrivacyAndPolicy.CLASS_NAME, typeof(PrivacyAndPolicy))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type PrivacyAndPolicy.
	/// </summary>
	public partial class PrivacyAndPolicy : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.PrivacyAndPolicy";


		/// <summary>
		/// The instance of the class that provides extended API for working with PrivacyAndPolicy fields.
		/// </summary>
		private readonly PrivacyAndPolicyFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PrivacyAndPolicyID.
		/// </summary>
		[DatabaseIDField]
		public int PrivacyAndPolicyID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PrivacyAndPolicyID"), 0);
			}
			set
			{
				SetValue("PrivacyAndPolicyID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Content.
		/// </summary>
		[DatabaseField]
		public string Content
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Content"), @"");
			}
			set
			{
				SetValue("Content", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PrivacyAndPolicy fields.
		/// </summary>
		[RegisterProperty]
		public PrivacyAndPolicyFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PrivacyAndPolicy fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PrivacyAndPolicyFields : AbstractHierarchicalObject<PrivacyAndPolicyFields>
		{
			/// <summary>
			/// The content item of type PrivacyAndPolicy that is a target of the extended API.
			/// </summary>
			private readonly PrivacyAndPolicy mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PrivacyAndPolicyFields" /> class with the specified content item of type PrivacyAndPolicy.
			/// </summary>
			/// <param name="instance">The content item of type PrivacyAndPolicy that is a target of the extended API.</param>
			public PrivacyAndPolicyFields(PrivacyAndPolicy instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PrivacyAndPolicyID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PrivacyAndPolicyID;
				}
				set
				{
					mInstance.PrivacyAndPolicyID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Content.
			/// </summary>
			public string Content
			{
				get
				{
					return mInstance.Content;
				}
				set
				{
					mInstance.Content = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PrivacyAndPolicy" /> class.
		/// </summary>
		public PrivacyAndPolicy() : base(CLASS_NAME)
		{
			mFields = new PrivacyAndPolicyFields(this);
		}

		#endregion
	}
}