//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Eurobank;

[assembly: RegisterCustomTable(TempAddressDetailsItem.CLASS_NAME, typeof(TempAddressDetailsItem))]

namespace CMS.CustomTables.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type TempAddressDetailsItem.
	/// </summary>
	public partial class TempAddressDetailsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.TempAddressDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with TempAddressDetailsItem fields.
		/// </summary>
		private readonly TempAddressDetailsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Personal Details ID .
		/// </summary>
		[DatabaseField]
		public string PersonalDetailsID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PersonalDetailsID"), @"");
			}
			set
			{
				SetValue("PersonalDetailsID", value);
			}
		}


		/// <summary>
		/// Address Type.
		/// </summary>
		[DatabaseField]
		public string AddressType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressType"), @"");
			}
			set
			{
				SetValue("AddressType", value);
			}
		}


		/// <summary>
		/// Street Lane 1.
		/// </summary>
		[DatabaseField]
		public string StreetLane1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("StreetLane1"), @"");
			}
			set
			{
				SetValue("StreetLane1", value);
			}
		}


		/// <summary>
		/// Street Lane 2.
		/// </summary>
		[DatabaseField]
		public string StreetLane2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("StreetLane2"), @"");
			}
			set
			{
				SetValue("StreetLane2", value);
			}
		}


		/// <summary>
		/// City.
		/// </summary>
		[DatabaseField]
		public string City
		{
			get
			{
				return ValidationHelper.GetString(GetValue("City"), @"");
			}
			set
			{
				SetValue("City", value);
			}
		}


		/// <summary>
		/// Postal Code.
		/// </summary>
		[DatabaseField]
		public string PostalCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PostalCode"), @"");
			}
			set
			{
				SetValue("PostalCode", value);
			}
		}


		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public string Country
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country"), @"");
			}
			set
			{
				SetValue("Country", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TempAddressDetailsItem fields.
		/// </summary>
		[RegisterProperty]
		public TempAddressDetailsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TempAddressDetailsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TempAddressDetailsItemFields : AbstractHierarchicalObject<TempAddressDetailsItemFields>
		{
			/// <summary>
			/// The content item of type TempAddressDetailsItem that is a target of the extended API.
			/// </summary>
			private readonly TempAddressDetailsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TempAddressDetailsItemFields" /> class with the specified content item of type TempAddressDetailsItem.
			/// </summary>
			/// <param name="instance">The content item of type TempAddressDetailsItem that is a target of the extended API.</param>
			public TempAddressDetailsItemFields(TempAddressDetailsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Personal Details ID .
			/// </summary>
			public string PersonalDetailsID
			{
				get
				{
					return mInstance.PersonalDetailsID;
				}
				set
				{
					mInstance.PersonalDetailsID = value;
				}
			}


			/// <summary>
			/// Address Type.
			/// </summary>
			public string AddressType
			{
				get
				{
					return mInstance.AddressType;
				}
				set
				{
					mInstance.AddressType = value;
				}
			}


			/// <summary>
			/// Street Lane 1.
			/// </summary>
			public string StreetLane1
			{
				get
				{
					return mInstance.StreetLane1;
				}
				set
				{
					mInstance.StreetLane1 = value;
				}
			}


			/// <summary>
			/// Street Lane 2.
			/// </summary>
			public string StreetLane2
			{
				get
				{
					return mInstance.StreetLane2;
				}
				set
				{
					mInstance.StreetLane2 = value;
				}
			}


			/// <summary>
			/// City.
			/// </summary>
			public string City
			{
				get
				{
					return mInstance.City;
				}
				set
				{
					mInstance.City = value;
				}
			}


			/// <summary>
			/// Postal Code.
			/// </summary>
			public string PostalCode
			{
				get
				{
					return mInstance.PostalCode;
				}
				set
				{
					mInstance.PostalCode = value;
				}
			}


			/// <summary>
			/// Country.
			/// </summary>
			public string Country
			{
				get
				{
					return mInstance.Country;
				}
				set
				{
					mInstance.Country = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TempAddressDetailsItem" /> class.
		/// </summary>
		public TempAddressDetailsItem() : base(CLASS_NAME)
		{
			mFields = new TempAddressDetailsItemFields(this);
		}

		#endregion
	}
}