//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Eurobank;

[assembly: RegisterCustomTable(TempPersonalDetailsItem.CLASS_NAME, typeof(TempPersonalDetailsItem))]

namespace CMS.CustomTables.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type TempPersonalDetailsItem.
	/// </summary>
	public partial class TempPersonalDetailsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.TempPersonalDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with TempPersonalDetailsItem fields.
		/// </summary>
		private readonly TempPersonalDetailsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Application ID.
		/// </summary>
		[DatabaseField]
		public string ApplicationID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationID"), @"");
			}
			set
			{
				SetValue("ApplicationID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Frist Name.
		/// </summary>
		[DatabaseField]
		public string FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FirstName"), @"");
			}
			set
			{
				SetValue("FirstName", value);
			}
		}


		/// <summary>
		/// Last Name.
		/// </summary>
		[DatabaseField]
		public string LastName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LastName"), @"");
			}
			set
			{
				SetValue("LastName", value);
			}
		}


		/// <summary>
		/// Father Name.
		/// </summary>
		[DatabaseField]
		public string FatherName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FatherName"), @"");
			}
			set
			{
				SetValue("FatherName", value);
			}
		}


		/// <summary>
		/// Date of Birth.
		/// </summary>
		[DatabaseField]
		public string DateofBirth
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DateofBirth"), @"");
			}
			set
			{
				SetValue("DateofBirth", value);
			}
		}


		/// <summary>
		/// Gender.
		/// </summary>
		[DatabaseField]
		public string Gender
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Gender"), @"");
			}
			set
			{
				SetValue("Gender", value);
			}
		}


		/// <summary>
		/// Place of Birth.
		/// </summary>
		[DatabaseField]
		public string PlaceofBirth
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PlaceofBirth"), @"");
			}
			set
			{
				SetValue("PlaceofBirth", value);
			}
		}


		/// <summary>
		/// Country of Birth.
		/// </summary>
		[DatabaseField]
		public string CountryofBirth
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CountryofBirth"), @"");
			}
			set
			{
				SetValue("CountryofBirth", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TempPersonalDetailsItem fields.
		/// </summary>
		[RegisterProperty]
		public TempPersonalDetailsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TempPersonalDetailsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TempPersonalDetailsItemFields : AbstractHierarchicalObject<TempPersonalDetailsItemFields>
		{
			/// <summary>
			/// The content item of type TempPersonalDetailsItem that is a target of the extended API.
			/// </summary>
			private readonly TempPersonalDetailsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TempPersonalDetailsItemFields" /> class with the specified content item of type TempPersonalDetailsItem.
			/// </summary>
			/// <param name="instance">The content item of type TempPersonalDetailsItem that is a target of the extended API.</param>
			public TempPersonalDetailsItemFields(TempPersonalDetailsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Application ID.
			/// </summary>
			public string ApplicationID
			{
				get
				{
					return mInstance.ApplicationID;
				}
				set
				{
					mInstance.ApplicationID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Frist Name.
			/// </summary>
			public string FirstName
			{
				get
				{
					return mInstance.FirstName;
				}
				set
				{
					mInstance.FirstName = value;
				}
			}


			/// <summary>
			/// Last Name.
			/// </summary>
			public string LastName
			{
				get
				{
					return mInstance.LastName;
				}
				set
				{
					mInstance.LastName = value;
				}
			}


			/// <summary>
			/// Father Name.
			/// </summary>
			public string FatherName
			{
				get
				{
					return mInstance.FatherName;
				}
				set
				{
					mInstance.FatherName = value;
				}
			}


			/// <summary>
			/// Date of Birth.
			/// </summary>
			public string DateofBirth
			{
				get
				{
					return mInstance.DateofBirth;
				}
				set
				{
					mInstance.DateofBirth = value;
				}
			}


			/// <summary>
			/// Gender.
			/// </summary>
			public string Gender
			{
				get
				{
					return mInstance.Gender;
				}
				set
				{
					mInstance.Gender = value;
				}
			}


			/// <summary>
			/// Place of Birth.
			/// </summary>
			public string PlaceofBirth
			{
				get
				{
					return mInstance.PlaceofBirth;
				}
				set
				{
					mInstance.PlaceofBirth = value;
				}
			}


			/// <summary>
			/// Country of Birth.
			/// </summary>
			public string CountryofBirth
			{
				get
				{
					return mInstance.CountryofBirth;
				}
				set
				{
					mInstance.CountryofBirth = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TempPersonalDetailsItem" /> class.
		/// </summary>
		public TempPersonalDetailsItem() : base(CLASS_NAME)
		{
			mFields = new TempPersonalDetailsItemFields(this);
		}

		#endregion
	}
}