//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(FAQ.CLASS_NAME, typeof(FAQ))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type FAQ.
	/// </summary>
	public partial class FAQ : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.FAQ";


		/// <summary>
		/// The instance of the class that provides extended API for working with FAQ fields.
		/// </summary>
		private readonly FAQFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FaqID.
		/// </summary>
		[DatabaseIDField]
		public int FaqID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FaqID"), 0);
			}
			set
			{
				SetValue("FaqID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Visit Us.
		/// </summary>
		[DatabaseField]
		public string VisitUs
		{
			get
			{
				return ValidationHelper.GetString(GetValue("VisitUs"), @"");
			}
			set
			{
				SetValue("VisitUs", value);
			}
		}


		/// <summary>
		/// Email Us.
		/// </summary>
		[DatabaseField]
		public string EmailUs
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmailUs"), @"");
			}
			set
			{
				SetValue("EmailUs", value);
			}
		}


		/// <summary>
		/// Call Us.
		/// </summary>
		[DatabaseField]
		public string CallUs
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CallUs"), @"");
			}
			set
			{
				SetValue("CallUs", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FAQ fields.
		/// </summary>
		[RegisterProperty]
		public FAQFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FAQ fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FAQFields : AbstractHierarchicalObject<FAQFields>
		{
			/// <summary>
			/// The content item of type FAQ that is a target of the extended API.
			/// </summary>
			private readonly FAQ mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FAQFields" /> class with the specified content item of type FAQ.
			/// </summary>
			/// <param name="instance">The content item of type FAQ that is a target of the extended API.</param>
			public FAQFields(FAQ instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FaqID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FaqID;
				}
				set
				{
					mInstance.FaqID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Visit Us.
			/// </summary>
			public string VisitUs
			{
				get
				{
					return mInstance.VisitUs;
				}
				set
				{
					mInstance.VisitUs = value;
				}
			}


			/// <summary>
			/// Email Us.
			/// </summary>
			public string EmailUs
			{
				get
				{
					return mInstance.EmailUs;
				}
				set
				{
					mInstance.EmailUs = value;
				}
			}


			/// <summary>
			/// Call Us.
			/// </summary>
			public string CallUs
			{
				get
				{
					return mInstance.CallUs;
				}
				set
				{
					mInstance.CallUs = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FAQ" /> class.
		/// </summary>
		public FAQ() : base(CLASS_NAME)
		{
			mFields = new FAQFields(this);
		}

		#endregion
	}
}