//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(FAQItem.CLASS_NAME, typeof(FAQItem))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type FAQItem.
	/// </summary>
	public partial class FAQItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.FAQItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with FAQItem fields.
		/// </summary>
		private readonly FAQItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FAQItemID.
		/// </summary>
		[DatabaseIDField]
		public int FAQItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FAQItemID"), 0);
			}
			set
			{
				SetValue("FAQItemID", value);
			}
		}


		/// <summary>
		/// Questions.
		/// </summary>
		[DatabaseField]
		public string Questions
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Questions"), @"");
			}
			set
			{
				SetValue("Questions", value);
			}
		}


		/// <summary>
		/// Answers.
		/// </summary>
		[DatabaseField]
		public string Answers
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Answers"), @"");
			}
			set
			{
				SetValue("Answers", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FAQItem fields.
		/// </summary>
		[RegisterProperty]
		public FAQItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FAQItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FAQItemFields : AbstractHierarchicalObject<FAQItemFields>
		{
			/// <summary>
			/// The content item of type FAQItem that is a target of the extended API.
			/// </summary>
			private readonly FAQItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FAQItemFields" /> class with the specified content item of type FAQItem.
			/// </summary>
			/// <param name="instance">The content item of type FAQItem that is a target of the extended API.</param>
			public FAQItemFields(FAQItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FAQItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FAQItemID;
				}
				set
				{
					mInstance.FAQItemID = value;
				}
			}


			/// <summary>
			/// Questions.
			/// </summary>
			public string Questions
			{
				get
				{
					return mInstance.Questions;
				}
				set
				{
					mInstance.Questions = value;
				}
			}


			/// <summary>
			/// Answers.
			/// </summary>
			public string Answers
			{
				get
				{
					return mInstance.Answers;
				}
				set
				{
					mInstance.Answers = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FAQItem" /> class.
		/// </summary>
		public FAQItem() : base(CLASS_NAME)
		{
			mFields = new FAQItemFields(this);
		}

		#endregion
	}
}