//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(DecisionHistory.CLASS_NAME, typeof(DecisionHistory))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type DecisionHistory.
	/// </summary>
	public partial class DecisionHistory : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.DecisionHistory";


		/// <summary>
		/// The instance of the class that provides extended API for working with DecisionHistory fields.
		/// </summary>
		private readonly DecisionHistoryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DecisionHistoryID.
		/// </summary>
		[DatabaseIDField]
		public int DecisionHistoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DecisionHistoryID"), 0);
			}
			set
			{
				SetValue("DecisionHistoryID", value);
			}
		}


		/// <summary>
		/// When.
		/// </summary>
		[DatabaseField]
		public DateTime DecisionHistory_When
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("DecisionHistory_When"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("DecisionHistory_When", value);
			}
		}


		/// <summary>
		/// Who.
		/// </summary>
		[DatabaseField]
		public string DecisionHistory_Who
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DecisionHistory_Who"), @"");
			}
			set
			{
				SetValue("DecisionHistory_Who", value);
			}
		}


		/// <summary>
		/// Stage.
		/// </summary>
		[DatabaseField]
		public string DecisionHistory_Stage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DecisionHistory_Stage"), @"");
			}
			set
			{
				SetValue("DecisionHistory_Stage", value);
			}
		}


		/// <summary>
		/// Decision.
		/// </summary>
		[DatabaseField]
		public string DecisionHistory_Decision
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DecisionHistory_Decision"), @"");
			}
			set
			{
				SetValue("DecisionHistory_Decision", value);
			}
		}


		/// <summary>
		/// Comments.
		/// </summary>
		[DatabaseField]
		public string DecisionHistory_Comments
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DecisionHistory_Comments"), @"");
			}
			set
			{
				SetValue("DecisionHistory_Comments", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DecisionHistory fields.
		/// </summary>
		[RegisterProperty]
		public DecisionHistoryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DecisionHistory fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DecisionHistoryFields : AbstractHierarchicalObject<DecisionHistoryFields>
		{
			/// <summary>
			/// The content item of type DecisionHistory that is a target of the extended API.
			/// </summary>
			private readonly DecisionHistory mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DecisionHistoryFields" /> class with the specified content item of type DecisionHistory.
			/// </summary>
			/// <param name="instance">The content item of type DecisionHistory that is a target of the extended API.</param>
			public DecisionHistoryFields(DecisionHistory instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DecisionHistoryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DecisionHistoryID;
				}
				set
				{
					mInstance.DecisionHistoryID = value;
				}
			}


			/// <summary>
			/// When.
			/// </summary>
			public DateTime _When
			{
				get
				{
					return mInstance.DecisionHistory_When;
				}
				set
				{
					mInstance.DecisionHistory_When = value;
				}
			}


			/// <summary>
			/// Who.
			/// </summary>
			public string _Who
			{
				get
				{
					return mInstance.DecisionHistory_Who;
				}
				set
				{
					mInstance.DecisionHistory_Who = value;
				}
			}


			/// <summary>
			/// Stage.
			/// </summary>
			public string _Stage
			{
				get
				{
					return mInstance.DecisionHistory_Stage;
				}
				set
				{
					mInstance.DecisionHistory_Stage = value;
				}
			}


			/// <summary>
			/// Decision.
			/// </summary>
			public string _Decision
			{
				get
				{
					return mInstance.DecisionHistory_Decision;
				}
				set
				{
					mInstance.DecisionHistory_Decision = value;
				}
			}


			/// <summary>
			/// Comments.
			/// </summary>
			public string _Comments
			{
				get
				{
					return mInstance.DecisionHistory_Comments;
				}
				set
				{
					mInstance.DecisionHistory_Comments = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DecisionHistory" /> class.
		/// </summary>
		public DecisionHistory() : base(CLASS_NAME)
		{
			mFields = new DecisionHistoryFields(this);
		}

		#endregion
	}
}