//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(CompanyCRSDetails.CLASS_NAME, typeof(CompanyCRSDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type CompanyCRSDetails.
	/// </summary>
	public partial class CompanyCRSDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.CompanyCRSDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with CompanyCRSDetails fields.
		/// </summary>
		private readonly CompanyCRSDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CompanyCRSDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int CompanyCRSDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CompanyCRSDetailsID"), 0);
			}
			set
			{
				SetValue("CompanyCRSDetailsID", value);
			}
		}


		/// <summary>
		/// CRS Classification.
		/// </summary>
		[DatabaseField]
		public string CompanyCRSDetails_CRSClassification
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyCRSDetails_CRSClassification"), @"");
			}
			set
			{
				SetValue("CompanyCRSDetails_CRSClassification", value);
			}
		}


		/// <summary>
		/// Type of Active Non-Financial Entity(NFE).
		/// </summary>
		[DatabaseField]
		public string CompanyCRSDetails_TypeofActiveNonFinancialEntity
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyCRSDetails_TypeofActiveNonFinancialEntity"), @"");
			}
			set
			{
				SetValue("CompanyCRSDetails_TypeofActiveNonFinancialEntity", value);
			}
		}


		/// <summary>
		/// Name of Established Securities Market.
		/// </summary>
		[DatabaseField]
		public string CompanyCRSDetails_NameofEstablishedSecuritiesMarket
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyCRSDetails_NameofEstablishedSecuritiesMarket"), @"");
			}
			set
			{
				SetValue("CompanyCRSDetails_NameofEstablishedSecuritiesMarket", value);
			}
		}


		/// <summary>
		/// Type of Financial Institution.
		/// </summary>
		[DatabaseField]
		public string CompanyCRSDetails_TypeofFinancialInstitution
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CompanyCRSDetails_TypeofFinancialInstitution"), @"");
			}
			set
			{
				SetValue("CompanyCRSDetails_TypeofFinancialInstitution", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CompanyCRSDetails fields.
		/// </summary>
		[RegisterProperty]
		public CompanyCRSDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CompanyCRSDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CompanyCRSDetailsFields : AbstractHierarchicalObject<CompanyCRSDetailsFields>
		{
			/// <summary>
			/// The content item of type CompanyCRSDetails that is a target of the extended API.
			/// </summary>
			private readonly CompanyCRSDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CompanyCRSDetailsFields" /> class with the specified content item of type CompanyCRSDetails.
			/// </summary>
			/// <param name="instance">The content item of type CompanyCRSDetails that is a target of the extended API.</param>
			public CompanyCRSDetailsFields(CompanyCRSDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CompanyCRSDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CompanyCRSDetailsID;
				}
				set
				{
					mInstance.CompanyCRSDetailsID = value;
				}
			}


			/// <summary>
			/// CRS Classification.
			/// </summary>
			public string _CRSClassification
			{
				get
				{
					return mInstance.CompanyCRSDetails_CRSClassification;
				}
				set
				{
					mInstance.CompanyCRSDetails_CRSClassification = value;
				}
			}


			/// <summary>
			/// Type of Active Non-Financial Entity(NFE).
			/// </summary>
			public string _TypeofActiveNonFinancialEntity
			{
				get
				{
					return mInstance.CompanyCRSDetails_TypeofActiveNonFinancialEntity;
				}
				set
				{
					mInstance.CompanyCRSDetails_TypeofActiveNonFinancialEntity = value;
				}
			}


			/// <summary>
			/// Name of Established Securities Market.
			/// </summary>
			public string _NameofEstablishedSecuritiesMarket
			{
				get
				{
					return mInstance.CompanyCRSDetails_NameofEstablishedSecuritiesMarket;
				}
				set
				{
					mInstance.CompanyCRSDetails_NameofEstablishedSecuritiesMarket = value;
				}
			}


			/// <summary>
			/// Type of Financial Institution.
			/// </summary>
			public string _TypeofFinancialInstitution
			{
				get
				{
					return mInstance.CompanyCRSDetails_TypeofFinancialInstitution;
				}
				set
				{
					mInstance.CompanyCRSDetails_TypeofFinancialInstitution = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CompanyCRSDetails" /> class.
		/// </summary>
		public CompanyCRSDetails() : base(CLASS_NAME)
		{
			mFields = new CompanyCRSDetailsFields(this);
		}

		#endregion
	}
}