//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(RelatedPartyRoles.CLASS_NAME, typeof(RelatedPartyRoles))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type RelatedPartyRoles.
	/// </summary>
	public partial class RelatedPartyRoles : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.RelatedPartyRoles";


		/// <summary>
		/// The instance of the class that provides extended API for working with RelatedPartyRoles fields.
		/// </summary>
		private readonly RelatedPartyRolesFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// RelatedPartyRolesID.
		/// </summary>
		[DatabaseIDField]
		public int RelatedPartyRolesID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("RelatedPartyRolesID"), 0);
			}
			set
			{
				SetValue("RelatedPartyRolesID", value);
			}
		}


		/// <summary>
		/// Attorney.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsAttorney
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsAttorney"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsAttorney", value);
			}
		}


		/// <summary>
		/// Cardholder.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsCardholder
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsCardholder"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsCardholder", value);
			}
		}


		/// <summary>
		/// Signatory.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsSignatory
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsSignatory"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsSignatory", value);
			}
		}


		/// <summary>
		/// Contact Person.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsContactPerson
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsContactPerson"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsContactPerson", value);
			}
		}


		/// <summary>
		/// E-Banking User.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsEBankingUser
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsEBankingUser"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsEBankingUser", value);
			}
		}


		/// <summary>
		/// Power of Attorney.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_HasPowerOfAttorney
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_HasPowerOfAttorney"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_HasPowerOfAttorney", value);
			}
		}


		/// <summary>
		/// Director.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsDirector
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsDirector"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsDirector", value);
			}
		}


		/// <summary>
		/// Alternative Director.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsAlternativeDirector
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsAlternativeDirector"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsAlternativeDirector", value);
			}
		}


		/// <summary>
		/// Secretary.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsSecretary
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsSecretary"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsSecretary", value);
			}
		}


		/// <summary>
		/// Partner.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsPartner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsPartner"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsPartner", value);
			}
		}


		/// <summary>
		/// Shareholder.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsShareholder
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsShareholder"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsShareholder", value);
			}
		}


		/// <summary>
		/// Ultimate Beneficiary Owner.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsUltimateBeneficiaryOwner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsUltimateBeneficiaryOwner"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsUltimateBeneficiaryOwner", value);
			}
		}


		/// <summary>
		/// Authorised Signatory.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsAuthorisedSignatory
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsAuthorisedSignatory"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsAuthorisedSignatory", value);
			}
		}


		/// <summary>
		/// Authorised Person.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsAuthorisedPerson
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsAuthorisedPerson"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsAuthorisedPerson", value);
			}
		}


		/// <summary>
		/// Designated E-Banking User.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsDesignatedEBankingUser
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsDesignatedEBankingUser"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsDesignatedEBankingUser", value);
			}
		}


		/// <summary>
		/// Authorised Cardholder.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsAuthorisedCardholder
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsAuthorisedCardholder"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsAuthorisedCardholder", value);
			}
		}


		/// <summary>
		/// Authorised Contact Person.
		/// </summary>
		[DatabaseField]
		public bool RelatedPartyRoles_IsAuthorisedContactPerson
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("RelatedPartyRoles_IsAuthorisedContactPerson"), false);
			}
			set
			{
				SetValue("RelatedPartyRoles_IsAuthorisedContactPerson", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with RelatedPartyRoles fields.
		/// </summary>
		[RegisterProperty]
		public RelatedPartyRolesFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with RelatedPartyRoles fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class RelatedPartyRolesFields : AbstractHierarchicalObject<RelatedPartyRolesFields>
		{
			/// <summary>
			/// The content item of type RelatedPartyRoles that is a target of the extended API.
			/// </summary>
			private readonly RelatedPartyRoles mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="RelatedPartyRolesFields" /> class with the specified content item of type RelatedPartyRoles.
			/// </summary>
			/// <param name="instance">The content item of type RelatedPartyRoles that is a target of the extended API.</param>
			public RelatedPartyRolesFields(RelatedPartyRoles instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// RelatedPartyRolesID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.RelatedPartyRolesID;
				}
				set
				{
					mInstance.RelatedPartyRolesID = value;
				}
			}


			/// <summary>
			/// Attorney.
			/// </summary>
			public bool _IsAttorney
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsAttorney;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsAttorney = value;
				}
			}


			/// <summary>
			/// Cardholder.
			/// </summary>
			public bool _IsCardholder
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsCardholder;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsCardholder = value;
				}
			}


			/// <summary>
			/// Signatory.
			/// </summary>
			public bool _IsSignatory
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsSignatory;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsSignatory = value;
				}
			}


			/// <summary>
			/// Contact Person.
			/// </summary>
			public bool _IsContactPerson
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsContactPerson;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsContactPerson = value;
				}
			}


			/// <summary>
			/// E-Banking User.
			/// </summary>
			public bool _IsEBankingUser
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsEBankingUser;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsEBankingUser = value;
				}
			}


			/// <summary>
			/// Power of Attorney.
			/// </summary>
			public bool _HasPowerOfAttorney
			{
				get
				{
					return mInstance.RelatedPartyRoles_HasPowerOfAttorney;
				}
				set
				{
					mInstance.RelatedPartyRoles_HasPowerOfAttorney = value;
				}
			}


			/// <summary>
			/// Director.
			/// </summary>
			public bool _IsDirector
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsDirector;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsDirector = value;
				}
			}


			/// <summary>
			/// Alternative Director.
			/// </summary>
			public bool _IsAlternativeDirector
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsAlternativeDirector;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsAlternativeDirector = value;
				}
			}


			/// <summary>
			/// Secretary.
			/// </summary>
			public bool _IsSecretary
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsSecretary;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsSecretary = value;
				}
			}


			/// <summary>
			/// Partner.
			/// </summary>
			public bool _IsPartner
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsPartner;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsPartner = value;
				}
			}


			/// <summary>
			/// Shareholder.
			/// </summary>
			public bool _IsShareholder
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsShareholder;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsShareholder = value;
				}
			}


			/// <summary>
			/// Ultimate Beneficiary Owner.
			/// </summary>
			public bool _IsUltimateBeneficiaryOwner
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsUltimateBeneficiaryOwner;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsUltimateBeneficiaryOwner = value;
				}
			}


			/// <summary>
			/// Authorised Signatory.
			/// </summary>
			public bool _IsAuthorisedSignatory
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsAuthorisedSignatory;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsAuthorisedSignatory = value;
				}
			}


			/// <summary>
			/// Authorised Person.
			/// </summary>
			public bool _IsAuthorisedPerson
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsAuthorisedPerson;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsAuthorisedPerson = value;
				}
			}


			/// <summary>
			/// Designated E-Banking User.
			/// </summary>
			public bool _IsDesignatedEBankingUser
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsDesignatedEBankingUser;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsDesignatedEBankingUser = value;
				}
			}


			/// <summary>
			/// Authorised Cardholder.
			/// </summary>
			public bool _IsAuthorisedCardholder
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsAuthorisedCardholder;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsAuthorisedCardholder = value;
				}
			}


			/// <summary>
			/// Authorised Contact Person.
			/// </summary>
			public bool _IsAuthorisedContactPerson
			{
				get
				{
					return mInstance.RelatedPartyRoles_IsAuthorisedContactPerson;
				}
				set
				{
					mInstance.RelatedPartyRoles_IsAuthorisedContactPerson = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="RelatedPartyRoles" /> class.
		/// </summary>
		public RelatedPartyRoles() : base(CLASS_NAME)
		{
			mFields = new RelatedPartyRolesFields(this);
		}

		#endregion
	}
}