//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(EBankingSubscriberDetails.CLASS_NAME, typeof(EBankingSubscriberDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type EBankingSubscriberDetails.
	/// </summary>
	public partial class EBankingSubscriberDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.EBankingSubscriberDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with EBankingSubscriberDetails fields.
		/// </summary>
		private readonly EBankingSubscriberDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// EbankingSubscriberDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int EbankingSubscriberDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("EbankingSubscriberDetailsID"), 0);
			}
			set
			{
				SetValue("EbankingSubscriberDetailsID", value);
			}
		}


		/// <summary>
		/// Signatory Group.
		/// </summary>
		[DatabaseField]
		public Guid EbankingSubscriberDetails_SignatoryGroup
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EbankingSubscriberDetails_SignatoryGroup"), Guid.Empty);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_SignatoryGroup", value);
			}
		}


		/// <summary>
		/// Limit Amount.
		/// </summary>
		[DatabaseField]
		public Guid EbankingSubscriberDetails_LimitAmount
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EbankingSubscriberDetails_LimitAmount"), Guid.Empty);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_LimitAmount", value);
			}
		}


		/// <summary>
		/// Subscriber Name .
		/// </summary>
		[DatabaseField]
		public string EbankingSubscriberDetails_Subscriber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EbankingSubscriberDetails_Subscriber"), @"");
			}
			set
			{
				SetValue("EbankingSubscriberDetails_Subscriber", value);
			}
		}


		/// <summary>
		/// Identity/Passport Number.
		/// </summary>
		[DatabaseField]
		public string EBankingSubscriberDetails_IdentityPassportNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EBankingSubscriberDetails_IdentityPassportNumber"), @"");
			}
			set
			{
				SetValue("EBankingSubscriberDetails_IdentityPassportNumber", value);
			}
		}


		/// <summary>
		/// Country of Issue.
		/// </summary>
		[DatabaseField]
		public string EBankingSubscriberDetails_CountryOfIssue
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EBankingSubscriberDetails_CountryOfIssue"), @"");
			}
			set
			{
				SetValue("EBankingSubscriberDetails_CountryOfIssue", value);
			}
		}


		/// <summary>
		/// Access Level.
		/// </summary>
		[DatabaseField]
		public Guid EbankingSubscriberDetails_AccessLevel
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EbankingSubscriberDetails_AccessLevel"), Guid.Empty);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_AccessLevel", value);
			}
		}


		/// <summary>
		/// Ebanking Subscriber Details Status.
		/// </summary>
		[DatabaseField]
		public bool EbankingSubscriberDetails_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EbankingSubscriberDetails_Status"), false);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_Status", value);
			}
		}


		/// <summary>
		/// Access to All personal accounts.
		/// </summary>
		[DatabaseField]
		public bool EbankingSubscriberDetails_AccessToAllPersonalAccounts
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EbankingSubscriberDetails_AccessToAllPersonalAccounts"), false);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_AccessToAllPersonalAccounts", value);
			}
		}


		/// <summary>
		///  Automatically add future Personal accounts.
		/// </summary>
		[DatabaseField]
		public bool EbankingSubscriberDetails_AutomaticallyAddFuturePersonalAccounts
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EbankingSubscriberDetails_AutomaticallyAddFuturePersonalAccounts"), false);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_AutomaticallyAddFuturePersonalAccounts", value);
			}
		}


		/// <summary>
		/// Receive eStatements.
		/// </summary>
		[DatabaseField]
		public bool EbankingSubscriberDetails_ReceiveEStatements
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("EbankingSubscriberDetails_ReceiveEStatements"), false);
			}
			set
			{
				SetValue("EbankingSubscriberDetails_ReceiveEStatements", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with EBankingSubscriberDetails fields.
		/// </summary>
		[RegisterProperty]
		public EBankingSubscriberDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with EBankingSubscriberDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class EBankingSubscriberDetailsFields : AbstractHierarchicalObject<EBankingSubscriberDetailsFields>
		{
			/// <summary>
			/// The content item of type EBankingSubscriberDetails that is a target of the extended API.
			/// </summary>
			private readonly EBankingSubscriberDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="EBankingSubscriberDetailsFields" /> class with the specified content item of type EBankingSubscriberDetails.
			/// </summary>
			/// <param name="instance">The content item of type EBankingSubscriberDetails that is a target of the extended API.</param>
			public EBankingSubscriberDetailsFields(EBankingSubscriberDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// EbankingSubscriberDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.EbankingSubscriberDetailsID;
				}
				set
				{
					mInstance.EbankingSubscriberDetailsID = value;
				}
			}


			/// <summary>
			/// Signatory Group.
			/// </summary>
			public Guid _SignatoryGroup
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_SignatoryGroup;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_SignatoryGroup = value;
				}
			}


			/// <summary>
			/// Limit Amount.
			/// </summary>
			public Guid _LimitAmount
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_LimitAmount;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_LimitAmount = value;
				}
			}


			/// <summary>
			/// Subscriber Name .
			/// </summary>
			public string _Subscriber
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_Subscriber;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_Subscriber = value;
				}
			}


			/// <summary>
			/// Identity/Passport Number.
			/// </summary>
			public string _IdentityPassportNumber
			{
				get
				{
					return mInstance.EBankingSubscriberDetails_IdentityPassportNumber;
				}
				set
				{
					mInstance.EBankingSubscriberDetails_IdentityPassportNumber = value;
				}
			}


			/// <summary>
			/// Country of Issue.
			/// </summary>
			public string _CountryOfIssue
			{
				get
				{
					return mInstance.EBankingSubscriberDetails_CountryOfIssue;
				}
				set
				{
					mInstance.EBankingSubscriberDetails_CountryOfIssue = value;
				}
			}


			/// <summary>
			/// Access Level.
			/// </summary>
			public Guid _AccessLevel
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_AccessLevel;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_AccessLevel = value;
				}
			}


			/// <summary>
			/// Ebanking Subscriber Details Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_Status;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_Status = value;
				}
			}


			/// <summary>
			/// Access to All personal accounts.
			/// </summary>
			public bool _AccessToAllPersonalAccounts
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_AccessToAllPersonalAccounts;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_AccessToAllPersonalAccounts = value;
				}
			}


			/// <summary>
			///  Automatically add future Personal accounts.
			/// </summary>
			public bool _AutomaticallyAddFuturePersonalAccounts
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_AutomaticallyAddFuturePersonalAccounts;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_AutomaticallyAddFuturePersonalAccounts = value;
				}
			}


			/// <summary>
			/// Receive eStatements.
			/// </summary>
			public bool _ReceiveEStatements
			{
				get
				{
					return mInstance.EbankingSubscriberDetails_ReceiveEStatements;
				}
				set
				{
					mInstance.EbankingSubscriberDetails_ReceiveEStatements = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="EBankingSubscriberDetails" /> class.
		/// </summary>
		public EBankingSubscriberDetails() : base(CLASS_NAME)
		{
			mFields = new EBankingSubscriberDetailsFields(this);
		}

		#endregion
	}
}