//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(ReasonForOpeningAccount.CLASS_NAME, typeof(ReasonForOpeningAccount))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type ReasonForOpeningAccount.
	/// </summary>
	public partial class ReasonForOpeningAccount : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.ReasonForOpeningAccount";


		/// <summary>
		/// The instance of the class that provides extended API for working with ReasonForOpeningAccount fields.
		/// </summary>
		private readonly ReasonForOpeningAccountFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ReasonForOpeningAccountID.
		/// </summary>
		[DatabaseIDField]
		public int ReasonForOpeningAccountID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ReasonForOpeningAccountID"), 0);
			}
			set
			{
				SetValue("ReasonForOpeningAccountID", value);
			}
		}


		/// <summary>
		/// Reason For OpeningAccount.
		/// </summary>
		[DatabaseField]
		public string ReasonForOpeningAcc
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ReasonForOpeningAcc"), @"");
			}
			set
			{
				SetValue("ReasonForOpeningAcc", value);
			}
		}


		/// <summary>
		/// Entity Type.
		/// </summary>
		[DatabaseField]
		public string Company_EntityType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Company_EntityType"), @"");
			}
			set
			{
				SetValue("Company_EntityType", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ReasonForOpeningAccount fields.
		/// </summary>
		[RegisterProperty]
		public ReasonForOpeningAccountFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ReasonForOpeningAccount fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ReasonForOpeningAccountFields : AbstractHierarchicalObject<ReasonForOpeningAccountFields>
		{
			/// <summary>
			/// The content item of type ReasonForOpeningAccount that is a target of the extended API.
			/// </summary>
			private readonly ReasonForOpeningAccount mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ReasonForOpeningAccountFields" /> class with the specified content item of type ReasonForOpeningAccount.
			/// </summary>
			/// <param name="instance">The content item of type ReasonForOpeningAccount that is a target of the extended API.</param>
			public ReasonForOpeningAccountFields(ReasonForOpeningAccount instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ReasonForOpeningAccountID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ReasonForOpeningAccountID;
				}
				set
				{
					mInstance.ReasonForOpeningAccountID = value;
				}
			}


			/// <summary>
			/// Reason For OpeningAccount.
			/// </summary>
			public string ReasonForOpeningAcc
			{
				get
				{
					return mInstance.ReasonForOpeningAcc;
				}
				set
				{
					mInstance.ReasonForOpeningAcc = value;
				}
			}


			/// <summary>
			/// Entity Type.
			/// </summary>
			public string Company_EntityType
			{
				get
				{
					return mInstance.Company_EntityType;
				}
				set
				{
					mInstance.Company_EntityType = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ReasonForOpeningAccount" /> class.
		/// </summary>
		public ReasonForOpeningAccount() : base(CLASS_NAME)
		{
			mFields = new ReasonForOpeningAccountFields(this);
		}

		#endregion
	}
}