using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eurobank.Helpers.Validation
{
    public enum ApplicationModule
    {
        PEP_DETAILS_APPLICANT,
        PEP_DETAILS_RELATED_PARTY,
        PEP_DETAILS_FAMILY_MEMBER_ASSOCIATES,
        TAX_DETAILS,
        IDENTIFICATION,
        PERSONAL_DETAILS,
        LEGAL_ENTITY_DETAILS,
        BUSINESS_AND_FINANCIAL_PROFILE_EMPLOYMENT_DETAILS,
        BUSINESS_PROFILE,
        EXISTING_BANK_RELATIONSHIP,
        APPLICANT_BANKRELATIONSHIP_LEGAL,
        FINANCIAL_INFORMATION,
        CONTACT_DETAILS,
        ORGIN_OF_ANNUAL_INCOME,
        ORIGIN_OF_TOTAL_ASSETS,
        ADDRESS_DETAILS,
        FATCA_DETAILS, 
        CRS_DETAILS,
        ACCOUNTS,
        BANK_ACCOUNT_PURPOSE_AND_ANTICIPATED_ACTIVITY,
        COUNTERPARTIES_OF_INCOMING_TRANSACTION,
        COUNTERPARTIES_OF_OUTGOING_TRANSACTION,
        SIGNATURE_MANDATE,
        EBANKING_SUBSCRIBERS,
        CARDS,
        DECISION_HISTORY,
        APPLICATION_ACCOUNT,
        GROUP_STRUCTURE,
        APPLICATION_APPLICANT,
        APPLICATION_RELATED_PARTY,
        APPLICANTS,
        //RELATED_PARTY_PERSONAL_DETAILS,
        RELATED_PARTY_BUSINESS_AND_FINANCIAL_PROFILE,
        RELATED_PARTY_CONTACT_DETAILS,
        RELATED_PARTIES,
        RELATED_PARTY_ADDRESS_DETAILS,
        RELATED_PARTY_IDENTIFICATION_DETAILS,
        RELATED_PARTY_ORIGIN_OF_TOTAL_ASSETS,
        RELATED_PARTY_PEP_DETAILS,
        RELATED_PARTY_PEP_DETAILS_FAMILY_MEMBER_ASSOCIATES,
        RELATED_PARTY_SOURCE_OF_INCOME,
        RELATED_PARTY_ROLES,
        APPLICATION_DEBITCARD_DETAILS,
        SIGNATORY_GROUP,
       
        APPLICATION_NOTE_DETAILS,
        APPLICATION_BANK_DOCUMENTS,
        APPLICATION_EXPECTED_DOCUMENTS,
        RELATEDPARTY_BUSINESS_PROFILE,
        RELATEDPARTY_PEP_DETAILS,
        PERSON_REGISTRY,
        COMMUNICATION_DETAILS
    }
}
