//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(OriginOfTotalAssets.CLASS_NAME, typeof(OriginOfTotalAssets))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type OriginOfTotalAssets.
	/// </summary>
	public partial class OriginOfTotalAssets : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.OriginOfTotalAssets";


		/// <summary>
		/// The instance of the class that provides extended API for working with OriginOfTotalAssets fields.
		/// </summary>
		private readonly OriginOfTotalAssetsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// OriginOfTotalAssetsID.
		/// </summary>
		[DatabaseIDField]
		public int OriginOfTotalAssetsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("OriginOfTotalAssetsID"), 0);
			}
			set
			{
				SetValue("OriginOfTotalAssetsID", value);
			}
		}


		/// <summary>
		/// Origin Of Total Assets.
		/// </summary>
		[DatabaseField]
		public Guid OriginOfTotalAssets_OriginOfTotalAssets
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("OriginOfTotalAssets_OriginOfTotalAssets"), Guid.Empty);
			}
			set
			{
				SetValue("OriginOfTotalAssets_OriginOfTotalAssets", value);
			}
		}


		/// <summary>
		/// Specify Other Origin.
		/// </summary>
		[DatabaseField]
		public string OriginOfTotalAssets_SpecifyOtherOrigin
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OriginOfTotalAssets_SpecifyOtherOrigin"), @"");
			}
			set
			{
				SetValue("OriginOfTotalAssets_SpecifyOtherOrigin", value);
			}
		}


		/// <summary>
		/// Amount of Total Asset.
		/// </summary>
		[DatabaseField]
		public double OriginOfTotalAssets_AmountOfTotalAsset
		{
			get
			{
				return ValidationHelper.GetDouble(GetValue("OriginOfTotalAssets_AmountOfTotalAsset"), 0);
			}
			set
			{
				SetValue("OriginOfTotalAssets_AmountOfTotalAsset", value);
			}
		}


		/// <summary>
		/// Is Confirmed.
		/// </summary>
		[DatabaseField]
		public bool Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Status"), false);
			}
			set
			{
				SetValue("Status", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with OriginOfTotalAssets fields.
		/// </summary>
		[RegisterProperty]
		public OriginOfTotalAssetsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with OriginOfTotalAssets fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class OriginOfTotalAssetsFields : AbstractHierarchicalObject<OriginOfTotalAssetsFields>
		{
			/// <summary>
			/// The content item of type OriginOfTotalAssets that is a target of the extended API.
			/// </summary>
			private readonly OriginOfTotalAssets mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="OriginOfTotalAssetsFields" /> class with the specified content item of type OriginOfTotalAssets.
			/// </summary>
			/// <param name="instance">The content item of type OriginOfTotalAssets that is a target of the extended API.</param>
			public OriginOfTotalAssetsFields(OriginOfTotalAssets instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// OriginOfTotalAssetsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.OriginOfTotalAssetsID;
				}
				set
				{
					mInstance.OriginOfTotalAssetsID = value;
				}
			}


			/// <summary>
			/// Origin Of Total Assets.
			/// </summary>
			public Guid _OriginOfTotalAssets
			{
				get
				{
					return mInstance.OriginOfTotalAssets_OriginOfTotalAssets;
				}
				set
				{
					mInstance.OriginOfTotalAssets_OriginOfTotalAssets = value;
				}
			}


			/// <summary>
			/// Specify Other Origin.
			/// </summary>
			public string _SpecifyOtherOrigin
			{
				get
				{
					return mInstance.OriginOfTotalAssets_SpecifyOtherOrigin;
				}
				set
				{
					mInstance.OriginOfTotalAssets_SpecifyOtherOrigin = value;
				}
			}


			/// <summary>
			/// Amount of Total Asset.
			/// </summary>
			public double _AmountOfTotalAsset
			{
				get
				{
					return mInstance.OriginOfTotalAssets_AmountOfTotalAsset;
				}
				set
				{
					mInstance.OriginOfTotalAssets_AmountOfTotalAsset = value;
				}
			}


			/// <summary>
			/// Is Confirmed.
			/// </summary>
			public bool Status
			{
				get
				{
					return mInstance.Status;
				}
				set
				{
					mInstance.Status = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="OriginOfTotalAssets" /> class.
		/// </summary>
		public OriginOfTotalAssets() : base(CLASS_NAME)
		{
			mFields = new OriginOfTotalAssetsFields(this);
		}

		#endregion
	}
}