//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(IdentificationDetails.CLASS_NAME, typeof(IdentificationDetails))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type IdentificationDetails.
	/// </summary>
	public partial class IdentificationDetails : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.IdentificationDetails";


		/// <summary>
		/// The instance of the class that provides extended API for working with IdentificationDetails fields.
		/// </summary>
		private readonly IdentificationDetailsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// IdentificationDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int IdentificationDetailsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("IdentificationDetailsID"), 0);
			}
			set
			{
				SetValue("IdentificationDetailsID", value);
			}
		}


		/// <summary>
		/// Citizenship.
		/// </summary>
		[DatabaseField]
		public int IdentificationDetails_Citizenship
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("IdentificationDetails_Citizenship"), 0);
			}
			set
			{
				SetValue("IdentificationDetails_Citizenship", value);
			}
		}


		/// <summary>
		/// Type of Identification.
		/// </summary>
		[DatabaseField]
		public Guid IdentificationDetails_TypeOfIdentification
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("IdentificationDetails_TypeOfIdentification"), Guid.Empty);
			}
			set
			{
				SetValue("IdentificationDetails_TypeOfIdentification", value);
			}
		}


		/// <summary>
		/// Identification Number .
		/// </summary>
		[DatabaseField]
		public string IdentificationDetails_IdentificationNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("IdentificationDetails_IdentificationNumber"), @"");
			}
			set
			{
				SetValue("IdentificationDetails_IdentificationNumber", value);
			}
		}


		/// <summary>
		/// Country of Issue.
		/// </summary>
		[DatabaseField]
		public int IdentificationDetails_CountryOfIssue
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("IdentificationDetails_CountryOfIssue"), 0);
			}
			set
			{
				SetValue("IdentificationDetails_CountryOfIssue", value);
			}
		}


		/// <summary>
		/// Issue Date.
		/// </summary>
		[DatabaseField]
		public DateTime IdentificationDetails_IssueDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("IdentificationDetails_IssueDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("IdentificationDetails_IssueDate", value);
			}
		}


		/// <summary>
		/// Expiry Date.
		/// </summary>
		[DatabaseField]
		public DateTime IdentificationDetails_ExpiryDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("IdentificationDetails_ExpiryDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("IdentificationDetails_ExpiryDate", value);
			}
		}


		/// <summary>
		/// Status.
		/// </summary>
		[DatabaseField]
		public bool IdentificationDetails_Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IdentificationDetails_Status"), false);
			}
			set
			{
				SetValue("IdentificationDetails_Status", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with IdentificationDetails fields.
		/// </summary>
		[RegisterProperty]
		public IdentificationDetailsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with IdentificationDetails fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class IdentificationDetailsFields : AbstractHierarchicalObject<IdentificationDetailsFields>
		{
			/// <summary>
			/// The content item of type IdentificationDetails that is a target of the extended API.
			/// </summary>
			private readonly IdentificationDetails mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="IdentificationDetailsFields" /> class with the specified content item of type IdentificationDetails.
			/// </summary>
			/// <param name="instance">The content item of type IdentificationDetails that is a target of the extended API.</param>
			public IdentificationDetailsFields(IdentificationDetails instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// IdentificationDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.IdentificationDetailsID;
				}
				set
				{
					mInstance.IdentificationDetailsID = value;
				}
			}


			/// <summary>
			/// Citizenship.
			/// </summary>
			public int _Citizenship
			{
				get
				{
					return mInstance.IdentificationDetails_Citizenship;
				}
				set
				{
					mInstance.IdentificationDetails_Citizenship = value;
				}
			}


			/// <summary>
			/// Type of Identification.
			/// </summary>
			public Guid _TypeOfIdentification
			{
				get
				{
					return mInstance.IdentificationDetails_TypeOfIdentification;
				}
				set
				{
					mInstance.IdentificationDetails_TypeOfIdentification = value;
				}
			}


			/// <summary>
			/// Identification Number .
			/// </summary>
			public string _IdentificationNumber
			{
				get
				{
					return mInstance.IdentificationDetails_IdentificationNumber;
				}
				set
				{
					mInstance.IdentificationDetails_IdentificationNumber = value;
				}
			}


			/// <summary>
			/// Country of Issue.
			/// </summary>
			public int _CountryOfIssue
			{
				get
				{
					return mInstance.IdentificationDetails_CountryOfIssue;
				}
				set
				{
					mInstance.IdentificationDetails_CountryOfIssue = value;
				}
			}


			/// <summary>
			/// Issue Date.
			/// </summary>
			public DateTime _IssueDate
			{
				get
				{
					return mInstance.IdentificationDetails_IssueDate;
				}
				set
				{
					mInstance.IdentificationDetails_IssueDate = value;
				}
			}


			/// <summary>
			/// Expiry Date.
			/// </summary>
			public DateTime _ExpiryDate
			{
				get
				{
					return mInstance.IdentificationDetails_ExpiryDate;
				}
				set
				{
					mInstance.IdentificationDetails_ExpiryDate = value;
				}
			}


			/// <summary>
			/// Status.
			/// </summary>
			public bool _Status
			{
				get
				{
					return mInstance.IdentificationDetails_Status;
				}
				set
				{
					mInstance.IdentificationDetails_Status = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="IdentificationDetails" /> class.
		/// </summary>
		public IdentificationDetails() : base(CLASS_NAME)
		{
			mFields = new IdentificationDetailsFields(this);
		}

		#endregion
	}
}