//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(EmploymentDetailsRelatedParty.CLASS_NAME, typeof(EmploymentDetailsRelatedParty))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type EmploymentDetailsRelatedParty.
	/// </summary>
	public partial class EmploymentDetailsRelatedParty : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.EmploymentDetailsRelatedParty";


		/// <summary>
		/// The instance of the class that provides extended API for working with EmploymentDetailsRelatedParty fields.
		/// </summary>
		private readonly EmploymentDetailsRelatedPartyFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// EmploymentDetailsID.
		/// </summary>
		[DatabaseIDField]
		public int EmploymentDetailsRelatedPartyID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("EmploymentDetailsRelatedPartyID"), 0);
			}
			set
			{
				SetValue("EmploymentDetailsRelatedPartyID", value);
			}
		}


		/// <summary>
		/// Employment Status.
		/// </summary>
		[DatabaseField]
		public Guid EmploymentDetails_EmploymentStatus
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EmploymentDetails_EmploymentStatus"), Guid.Empty);
			}
			set
			{
				SetValue("EmploymentDetails_EmploymentStatus", value);
			}
		}


		/// <summary>
		/// Profession.
		/// </summary>
		[DatabaseField]
		public Guid EmploymentDetails_Profession
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EmploymentDetails_Profession"), Guid.Empty);
			}
			set
			{
				SetValue("EmploymentDetails_Profession", value);
			}
		}


		/// <summary>
		/// Employer's Name.
		/// </summary>
		[DatabaseField]
		public string EmploymentDetails_EmployersName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmploymentDetails_EmployersName"), @"");
			}
			set
			{
				SetValue("EmploymentDetails_EmployersName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with EmploymentDetailsRelatedParty fields.
		/// </summary>
		[RegisterProperty]
		public EmploymentDetailsRelatedPartyFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with EmploymentDetailsRelatedParty fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class EmploymentDetailsRelatedPartyFields : AbstractHierarchicalObject<EmploymentDetailsRelatedPartyFields>
		{
			/// <summary>
			/// The content item of type EmploymentDetailsRelatedParty that is a target of the extended API.
			/// </summary>
			private readonly EmploymentDetailsRelatedParty mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="EmploymentDetailsRelatedPartyFields" /> class with the specified content item of type EmploymentDetailsRelatedParty.
			/// </summary>
			/// <param name="instance">The content item of type EmploymentDetailsRelatedParty that is a target of the extended API.</param>
			public EmploymentDetailsRelatedPartyFields(EmploymentDetailsRelatedParty instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// EmploymentDetailsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.EmploymentDetailsRelatedPartyID;
				}
				set
				{
					mInstance.EmploymentDetailsRelatedPartyID = value;
				}
			}


			/// <summary>
			/// Employment Status.
			/// </summary>
			public Guid EmploymentDetails_EmploymentStatus
			{
				get
				{
					return mInstance.EmploymentDetails_EmploymentStatus;
				}
				set
				{
					mInstance.EmploymentDetails_EmploymentStatus = value;
				}
			}


			/// <summary>
			/// Profession.
			/// </summary>
			public Guid EmploymentDetails_Profession
			{
				get
				{
					return mInstance.EmploymentDetails_Profession;
				}
				set
				{
					mInstance.EmploymentDetails_Profession = value;
				}
			}


			/// <summary>
			/// Employer's Name.
			/// </summary>
			public string EmploymentDetails_EmployersName
			{
				get
				{
					return mInstance.EmploymentDetails_EmployersName;
				}
				set
				{
					mInstance.EmploymentDetails_EmployersName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="EmploymentDetailsRelatedParty" /> class.
		/// </summary>
		public EmploymentDetailsRelatedParty() : base(CLASS_NAME)
		{
			mFields = new EmploymentDetailsRelatedPartyFields(this);
		}

		#endregion
	}
}