//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(AddressRegistry.CLASS_NAME, typeof(AddressRegistry))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type AddressRegistry.
	/// </summary>
	public partial class AddressRegistry : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.AddressRegistry";


		/// <summary>
		/// The instance of the class that provides extended API for working with AddressRegistry fields.
		/// </summary>
		private readonly AddressRegistryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AddressRegistryID.
		/// </summary>
		[DatabaseIDField]
		public int AddressRegistryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AddressRegistryID"), 0);
			}
			set
			{
				SetValue("AddressRegistryID", value);
			}
		}


		/// <summary>
		/// Country code Phone no .
		/// </summary>
		[DatabaseField]
		public string CountryCode_PhoneNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CountryCode_PhoneNo"), @"");
			}
			set
			{
				SetValue("CountryCode_PhoneNo", value);
			}
		}


		/// <summary>
		/// Phone no.
		/// </summary>
		[DatabaseField]
		public string PhoneNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhoneNo"), @"");
			}
			set
			{
				SetValue("PhoneNo", value);
			}
		}


		/// <summary>
		/// Country Code Fax no.
		/// </summary>
		[DatabaseField]
		public string CountryCode_FaxNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CountryCode_FaxNo"), @"");
			}
			set
			{
				SetValue("CountryCode_FaxNo", value);
			}
		}


		/// <summary>
		/// Fax no.
		/// </summary>
		[DatabaseField]
		public string FaxNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FaxNo"), @"");
			}
			set
			{
				SetValue("FaxNo", value);
			}
		}


		/// <summary>
		/// Address Type.
		/// </summary>
		[DatabaseField]
		public string AddressType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddressType"), @"");
			}
			set
			{
				SetValue("AddressType", value);
			}
		}


		/// <summary>
		/// Location Name.
		/// </summary>
		[DatabaseField]
		public string LocationName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LocationName"), @"");
			}
			set
			{
				SetValue("LocationName", value);
			}
		}


		/// <summary>
		/// Address Line 1.
		/// </summary>
		[DatabaseField]
		public string AddresLine1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddresLine1"), @"");
			}
			set
			{
				SetValue("AddresLine1", value);
			}
		}


		/// <summary>
		/// Address Line2.
		/// </summary>
		[DatabaseField]
		public string AddresLine2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AddresLine2"), @"");
			}
			set
			{
				SetValue("AddresLine2", value);
			}
		}


		/// <summary>
		/// Postal Code.
		/// </summary>
		[DatabaseField]
		public string PostalCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PostalCode"), @"");
			}
			set
			{
				SetValue("PostalCode", value);
			}
		}


		/// <summary>
		/// P.O. Box.
		/// </summary>
		[DatabaseField]
		public string POBox
		{
			get
			{
				return ValidationHelper.GetString(GetValue("POBox"), @"");
			}
			set
			{
				SetValue("POBox", value);
			}
		}


		/// <summary>
		/// City.
		/// </summary>
		[DatabaseField]
		public string City
		{
			get
			{
				return ValidationHelper.GetString(GetValue("City"), @"");
			}
			set
			{
				SetValue("City", value);
			}
		}


		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public string Country
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country"), @"");
			}
			set
			{
				SetValue("Country", value);
			}
		}


		/// <summary>
		/// User Organization.
		/// </summary>
		[DatabaseField]
		public Guid UserOrganization
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("UserOrganization"), Guid.Empty);
			}
			set
			{
				SetValue("UserOrganization", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AddressRegistry fields.
		/// </summary>
		[RegisterProperty]
		public AddressRegistryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AddressRegistry fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AddressRegistryFields : AbstractHierarchicalObject<AddressRegistryFields>
		{
			/// <summary>
			/// The content item of type AddressRegistry that is a target of the extended API.
			/// </summary>
			private readonly AddressRegistry mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AddressRegistryFields" /> class with the specified content item of type AddressRegistry.
			/// </summary>
			/// <param name="instance">The content item of type AddressRegistry that is a target of the extended API.</param>
			public AddressRegistryFields(AddressRegistry instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AddressRegistryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AddressRegistryID;
				}
				set
				{
					mInstance.AddressRegistryID = value;
				}
			}


			/// <summary>
			/// Country code Phone no .
			/// </summary>
			public string CountryCode_PhoneNo
			{
				get
				{
					return mInstance.CountryCode_PhoneNo;
				}
				set
				{
					mInstance.CountryCode_PhoneNo = value;
				}
			}


			/// <summary>
			/// Phone no.
			/// </summary>
			public string PhoneNo
			{
				get
				{
					return mInstance.PhoneNo;
				}
				set
				{
					mInstance.PhoneNo = value;
				}
			}


			/// <summary>
			/// Country Code Fax no.
			/// </summary>
			public string CountryCode_FaxNo
			{
				get
				{
					return mInstance.CountryCode_FaxNo;
				}
				set
				{
					mInstance.CountryCode_FaxNo = value;
				}
			}


			/// <summary>
			/// Fax no.
			/// </summary>
			public string FaxNo
			{
				get
				{
					return mInstance.FaxNo;
				}
				set
				{
					mInstance.FaxNo = value;
				}
			}


			/// <summary>
			/// Address Type.
			/// </summary>
			public string AddressType
			{
				get
				{
					return mInstance.AddressType;
				}
				set
				{
					mInstance.AddressType = value;
				}
			}


			/// <summary>
			/// Location Name.
			/// </summary>
			public string LocationName
			{
				get
				{
					return mInstance.LocationName;
				}
				set
				{
					mInstance.LocationName = value;
				}
			}


			/// <summary>
			/// Address Line 1.
			/// </summary>
			public string AddresLine1
			{
				get
				{
					return mInstance.AddresLine1;
				}
				set
				{
					mInstance.AddresLine1 = value;
				}
			}


			/// <summary>
			/// Address Line2.
			/// </summary>
			public string AddresLine2
			{
				get
				{
					return mInstance.AddresLine2;
				}
				set
				{
					mInstance.AddresLine2 = value;
				}
			}


			/// <summary>
			/// Postal Code.
			/// </summary>
			public string PostalCode
			{
				get
				{
					return mInstance.PostalCode;
				}
				set
				{
					mInstance.PostalCode = value;
				}
			}


			/// <summary>
			/// P.O. Box.
			/// </summary>
			public string POBox
			{
				get
				{
					return mInstance.POBox;
				}
				set
				{
					mInstance.POBox = value;
				}
			}


			/// <summary>
			/// City.
			/// </summary>
			public string City
			{
				get
				{
					return mInstance.City;
				}
				set
				{
					mInstance.City = value;
				}
			}


			/// <summary>
			/// Country.
			/// </summary>
			public string Country
			{
				get
				{
					return mInstance.Country;
				}
				set
				{
					mInstance.Country = value;
				}
			}


			/// <summary>
			/// User Organization.
			/// </summary>
			public Guid UserOrganization
			{
				get
				{
					return mInstance.UserOrganization;
				}
				set
				{
					mInstance.UserOrganization = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AddressRegistry" /> class.
		/// </summary>
		public AddressRegistry() : base(CLASS_NAME)
		{
			mFields = new AddressRegistryFields(this);
		}

		#endregion
	}
}