//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Eurobank;

[assembly: RegisterDocumentType(PersonsRegistry.CLASS_NAME, typeof(PersonsRegistry))]

namespace CMS.DocumentEngine.Types.Eurobank
{
	/// <summary>
	/// Represents a content item of type PersonsRegistry.
	/// </summary>
	public partial class PersonsRegistry : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Eurobank.PersonsRegistry";


		/// <summary>
		/// The instance of the class that provides extended API for working with PersonsRegistry fields.
		/// </summary>
		private readonly PersonsRegistryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PersonsRegistryID.
		/// </summary>
		[DatabaseIDField]
		public int PersonsRegistryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PersonsRegistryID"), 0);
			}
			set
			{
				SetValue("PersonsRegistryID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Application Type.
		/// </summary>
		[DatabaseField]
		public string ApplicationType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ApplicationType"), @"");
			}
			set
			{
				SetValue("ApplicationType", value);
			}
		}


		/// <summary>
		/// Drop Down list 
		/// .
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// First Name.
		/// </summary>
		[DatabaseField]
		public string FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FirstName"), @"");
			}
			set
			{
				SetValue("FirstName", value);
			}
		}


		/// <summary>
		/// Last Name.
		/// </summary>
		[DatabaseField]
		public string LastName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LastName"), @"");
			}
			set
			{
				SetValue("LastName", value);
			}
		}


		/// <summary>
		/// Father's Name.
		/// </summary>
		[DatabaseField]
		public string FathersName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FathersName"), @"");
			}
			set
			{
				SetValue("FathersName", value);
			}
		}


		/// <summary>
		/// Drop Down list .
		/// </summary>
		[DatabaseField]
		public string Gender
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Gender"), @"");
			}
			set
			{
				SetValue("Gender", value);
			}
		}


		/// <summary>
		/// Date of Birth .
		/// </summary>
		[DatabaseField]
		public DateTime DateofBirth
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("DateofBirth"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("DateofBirth", value);
			}
		}


		/// <summary>
		/// Place of Birth.
		/// </summary>
		[DatabaseField]
		public string PlaceofBirth
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PlaceofBirth"), @"");
			}
			set
			{
				SetValue("PlaceofBirth", value);
			}
		}


		/// <summary>
		/// Drop Down list .
		/// </summary>
		[DatabaseField]
		public string CountryofBirth
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CountryofBirth"), @"");
			}
			set
			{
				SetValue("CountryofBirth", value);
			}
		}


		/// <summary>
		/// Education Level.
		/// </summary>
		[DatabaseField]
		public string EducationLevel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EducationLevel"), @"");
			}
			set
			{
				SetValue("EducationLevel", value);
			}
		}


		/// <summary>
		/// Drop Down list .
		/// </summary>
		[DatabaseField]
		public string Citizenship
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Citizenship"), @"");
			}
			set
			{
				SetValue("Citizenship", value);
			}
		}


		/// <summary>
		/// Drop Down list .
		/// </summary>
		[DatabaseField]
		public string TypeofIdentification
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TypeofIdentification"), @"");
			}
			set
			{
				SetValue("TypeofIdentification", value);
			}
		}


		/// <summary>
		/// Identification Number.
		/// </summary>
		[DatabaseField]
		public string IdentificationNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("IdentificationNumber"), @"");
			}
			set
			{
				SetValue("IdentificationNumber", value);
			}
		}


		/// <summary>
		/// Issuing Country.
		/// </summary>
		[DatabaseField]
		public string IssuingCountry
		{
			get
			{
				return ValidationHelper.GetString(GetValue("IssuingCountry"), @"");
			}
			set
			{
				SetValue("IssuingCountry", value);
			}
		}


		/// <summary>
		/// Issue Date .
		/// </summary>
		[DatabaseField]
		public DateTime IssueDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("IssueDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("IssueDate", value);
			}
		}


		/// <summary>
		/// Expiry Date.
		/// </summary>
		[DatabaseField]
		public DateTime ExpiryDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ExpiryDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ExpiryDate", value);
			}
		}


		/// <summary>
		/// Mobile Tel No.(Incl. country code).
		/// </summary>
		[DatabaseField]
		public string MobileTelNoCountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MobileTelNoCountryCode"), @"");
			}
			set
			{
				SetValue("MobileTelNoCountryCode", value);
			}
		}


		/// <summary>
		/// Mobile Tel No Number.
		/// </summary>
		[DatabaseField]
		public string MobileTelNoNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MobileTelNoNumber"), @"");
			}
			set
			{
				SetValue("MobileTelNoNumber", value);
			}
		}


		/// <summary>
		/// Home Tel No.(Incl. country code).
		/// </summary>
		[DatabaseField]
		public string HomeTelNoCountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeTelNoCountryCode"), @"");
			}
			set
			{
				SetValue("HomeTelNoCountryCode", value);
			}
		}


		/// <summary>
		/// HomeTelNoNumber.
		/// </summary>
		[DatabaseField]
		public string HomeTelNoNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeTelNoNumber"), @"");
			}
			set
			{
				SetValue("HomeTelNoNumber", value);
			}
		}


		/// <summary>
		/// Work Tel No.(Incl. country code).
		/// </summary>
		[DatabaseField]
		public string WorkTelNoCountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WorkTelNoCountryCode"), @"");
			}
			set
			{
				SetValue("WorkTelNoCountryCode", value);
			}
		}


		/// <summary>
		/// Work Tel No.
		/// </summary>
		[DatabaseField]
		public string WorkTelNoNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WorkTelNoNumber"), @"");
			}
			set
			{
				SetValue("WorkTelNoNumber", value);
			}
		}


		/// <summary>
		/// Fax No.(Incl. country code).
		/// </summary>
		[DatabaseField]
		public string FaxNoCountryCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FaxNoCountryCode"), @"");
			}
			set
			{
				SetValue("FaxNoCountryCode", value);
			}
		}


		/// <summary>
		/// Fax No.
		/// </summary>
		[DatabaseField]
		public string FaxNoFaxNumber
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FaxNoFaxNumber"), @"");
			}
			set
			{
				SetValue("FaxNoFaxNumber", value);
			}
		}


		/// <summary>
		/// EmailAddress.
		/// </summary>
		[DatabaseField]
		public string EmailAddress
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmailAddress"), @"");
			}
			set
			{
				SetValue("EmailAddress", value);
			}
		}


		/// <summary>
		/// Preferred Communication Language.
		/// </summary>
		[DatabaseField]
		public string PreferredCommunicationLanguage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PreferredCommunicationLanguage"), @"");
			}
			set
			{
				SetValue("PreferredCommunicationLanguage", value);
			}
		}


		/// <summary>
		/// Consent for Marketing Purposes.
		/// </summary>
		[DatabaseField]
		public string ConsentforMarketingPurposes
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ConsentforMarketingPurposes"), @"");
			}
			set
			{
				SetValue("ConsentforMarketingPurposes", value);
			}
		}


		/// <summary>
		/// User Organization.
		/// </summary>
		[DatabaseField]
		public Guid UserOrganization
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("UserOrganization"), Guid.Empty);
			}
			set
			{
				SetValue("UserOrganization", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PersonsRegistry fields.
		/// </summary>
		[RegisterProperty]
		public PersonsRegistryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PersonsRegistry fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PersonsRegistryFields : AbstractHierarchicalObject<PersonsRegistryFields>
		{
			/// <summary>
			/// The content item of type PersonsRegistry that is a target of the extended API.
			/// </summary>
			private readonly PersonsRegistry mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PersonsRegistryFields" /> class with the specified content item of type PersonsRegistry.
			/// </summary>
			/// <param name="instance">The content item of type PersonsRegistry that is a target of the extended API.</param>
			public PersonsRegistryFields(PersonsRegistry instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PersonsRegistryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PersonsRegistryID;
				}
				set
				{
					mInstance.PersonsRegistryID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Application Type.
			/// </summary>
			public string ApplicationType
			{
				get
				{
					return mInstance.ApplicationType;
				}
				set
				{
					mInstance.ApplicationType = value;
				}
			}


			/// <summary>
			/// Drop Down list 
			/// .
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// First Name.
			/// </summary>
			public string FirstName
			{
				get
				{
					return mInstance.FirstName;
				}
				set
				{
					mInstance.FirstName = value;
				}
			}


			/// <summary>
			/// Last Name.
			/// </summary>
			public string LastName
			{
				get
				{
					return mInstance.LastName;
				}
				set
				{
					mInstance.LastName = value;
				}
			}


			/// <summary>
			/// Father's Name.
			/// </summary>
			public string FathersName
			{
				get
				{
					return mInstance.FathersName;
				}
				set
				{
					mInstance.FathersName = value;
				}
			}


			/// <summary>
			/// Drop Down list .
			/// </summary>
			public string Gender
			{
				get
				{
					return mInstance.Gender;
				}
				set
				{
					mInstance.Gender = value;
				}
			}


			/// <summary>
			/// Date of Birth .
			/// </summary>
			public DateTime DateofBirth
			{
				get
				{
					return mInstance.DateofBirth;
				}
				set
				{
					mInstance.DateofBirth = value;
				}
			}


			/// <summary>
			/// Place of Birth.
			/// </summary>
			public string PlaceofBirth
			{
				get
				{
					return mInstance.PlaceofBirth;
				}
				set
				{
					mInstance.PlaceofBirth = value;
				}
			}


			/// <summary>
			/// Drop Down list .
			/// </summary>
			public string CountryofBirth
			{
				get
				{
					return mInstance.CountryofBirth;
				}
				set
				{
					mInstance.CountryofBirth = value;
				}
			}


			/// <summary>
			/// Education Level.
			/// </summary>
			public string EducationLevel
			{
				get
				{
					return mInstance.EducationLevel;
				}
				set
				{
					mInstance.EducationLevel = value;
				}
			}


			/// <summary>
			/// Drop Down list .
			/// </summary>
			public string Citizenship
			{
				get
				{
					return mInstance.Citizenship;
				}
				set
				{
					mInstance.Citizenship = value;
				}
			}


			/// <summary>
			/// Drop Down list .
			/// </summary>
			public string TypeofIdentification
			{
				get
				{
					return mInstance.TypeofIdentification;
				}
				set
				{
					mInstance.TypeofIdentification = value;
				}
			}


			/// <summary>
			/// Identification Number.
			/// </summary>
			public string IdentificationNumber
			{
				get
				{
					return mInstance.IdentificationNumber;
				}
				set
				{
					mInstance.IdentificationNumber = value;
				}
			}


			/// <summary>
			/// Issuing Country.
			/// </summary>
			public string IssuingCountry
			{
				get
				{
					return mInstance.IssuingCountry;
				}
				set
				{
					mInstance.IssuingCountry = value;
				}
			}


			/// <summary>
			/// Issue Date .
			/// </summary>
			public DateTime IssueDate
			{
				get
				{
					return mInstance.IssueDate;
				}
				set
				{
					mInstance.IssueDate = value;
				}
			}


			/// <summary>
			/// Expiry Date.
			/// </summary>
			public DateTime ExpiryDate
			{
				get
				{
					return mInstance.ExpiryDate;
				}
				set
				{
					mInstance.ExpiryDate = value;
				}
			}


			/// <summary>
			/// Mobile Tel No.(Incl. country code).
			/// </summary>
			public string MobileTelNoCountryCode
			{
				get
				{
					return mInstance.MobileTelNoCountryCode;
				}
				set
				{
					mInstance.MobileTelNoCountryCode = value;
				}
			}


			/// <summary>
			/// Mobile Tel No Number.
			/// </summary>
			public string MobileTelNoNumber
			{
				get
				{
					return mInstance.MobileTelNoNumber;
				}
				set
				{
					mInstance.MobileTelNoNumber = value;
				}
			}


			/// <summary>
			/// Home Tel No.(Incl. country code).
			/// </summary>
			public string HomeTelNoCountryCode
			{
				get
				{
					return mInstance.HomeTelNoCountryCode;
				}
				set
				{
					mInstance.HomeTelNoCountryCode = value;
				}
			}


			/// <summary>
			/// HomeTelNoNumber.
			/// </summary>
			public string HomeTelNoNumber
			{
				get
				{
					return mInstance.HomeTelNoNumber;
				}
				set
				{
					mInstance.HomeTelNoNumber = value;
				}
			}


			/// <summary>
			/// Work Tel No.(Incl. country code).
			/// </summary>
			public string WorkTelNoCountryCode
			{
				get
				{
					return mInstance.WorkTelNoCountryCode;
				}
				set
				{
					mInstance.WorkTelNoCountryCode = value;
				}
			}


			/// <summary>
			/// Work Tel No.
			/// </summary>
			public string WorkTelNoNumber
			{
				get
				{
					return mInstance.WorkTelNoNumber;
				}
				set
				{
					mInstance.WorkTelNoNumber = value;
				}
			}


			/// <summary>
			/// Fax No.(Incl. country code).
			/// </summary>
			public string FaxNoCountryCode
			{
				get
				{
					return mInstance.FaxNoCountryCode;
				}
				set
				{
					mInstance.FaxNoCountryCode = value;
				}
			}


			/// <summary>
			/// Fax No.
			/// </summary>
			public string FaxNoFaxNumber
			{
				get
				{
					return mInstance.FaxNoFaxNumber;
				}
				set
				{
					mInstance.FaxNoFaxNumber = value;
				}
			}


			/// <summary>
			/// EmailAddress.
			/// </summary>
			public string EmailAddress
			{
				get
				{
					return mInstance.EmailAddress;
				}
				set
				{
					mInstance.EmailAddress = value;
				}
			}


			/// <summary>
			/// Preferred Communication Language.
			/// </summary>
			public string PreferredCommunicationLanguage
			{
				get
				{
					return mInstance.PreferredCommunicationLanguage;
				}
				set
				{
					mInstance.PreferredCommunicationLanguage = value;
				}
			}


			/// <summary>
			/// Consent for Marketing Purposes.
			/// </summary>
			public string ConsentforMarketingPurposes
			{
				get
				{
					return mInstance.ConsentforMarketingPurposes;
				}
				set
				{
					mInstance.ConsentforMarketingPurposes = value;
				}
			}


			/// <summary>
			/// User Organization.
			/// </summary>
			public Guid UserOrganization
			{
				get
				{
					return mInstance.UserOrganization;
				}
				set
				{
					mInstance.UserOrganization = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PersonsRegistry" /> class.
		/// </summary>
		public PersonsRegistry() : base(CLASS_NAME)
		{
			mFields = new PersonsRegistryFields(this);
		}

		#endregion
	}
}